## Child mortality prediction - data preparation part 2
Check all the datasets we need and only keep the rows and columns we need

### Repeat the data transformations we did in data preparation part 1 for all the other WHO regions
We've prepared the data for the Region of the Americas in the previous Notebook.
Now we do it for the African region, Eastern mediterranean region, European region, South-east asian region, Western pacific region. Let's do it one region at a time.

In [1]:
## Load CSV file containing data for a WHO Region 
import pandas as pd
import numpy as np
import scipy.stats as stats

url = 'child_mort_data/child_mortality_western-pacific.csv'
df = pd.read_csv(url, delimiter=',')
print(f"df type: {type(df)}")   ## df type: <class 'pandas.core.frame.DataFrame'>
print(f"df shape: {df.shape}")  ## df shape: (3055, 8)'

df type: <class 'pandas.core.frame.DataFrame'>
df shape: (1778, 8)

In [2]:
## Check the details of the dataset 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1778 entries, 0 to 1777
Data columns (total 8 columns):
 #   Column                                                          Non-Null Count  Dtype
---  ------                                                          --------------  -----
 0   Unnamed: 0                                                      1778 non-null   object
 1   Unnamed: 1                                                      1778 non-null   object
 2   Under-five mortality rate (per 1000 live births) (SDG 3.2.1)    1778 non-null   object
 3   Under-five mortality rate (per 1000 live births) (SDG 3.2.1).1  1715 non-null   object
 4   Under-five mortality rate (per 1000 live births) (SDG 3.2.1).2  1715 non-null   object
 5   Number of deaths among children under-five                      1580 non-null   object
 6   Number of deaths among children under-five.1                    1580 non-null   object
 7   Number of deaths among children under-five.2                    1580 non-null   object
dtypes: object(8)
memory usage: 111.2+ KB

In [3]:
## Check the fisrt rows of the dataset
df.head(8)

,Unnamed: 0,Unnamed: 1,Under-five mortality rate (per 1000 live births) (SDG 3.2.1),Under-five mortality rate (per 1000 live births) (SDG 3.2.1).1,Under-five mortality rate (per 1000 live births) (SDG 3.2.1).2,Number of deaths among children under-five,Number of deaths among children under-five.1,Number of deaths among children under-five.2
0,"Countries, territories and areas",Year,Both sexes,Male,Female,Both sexes,Male,Female
1,Australia,2021,3.71 [3.5-3.94],4.04 [3.8-4.29],3.37 [3.16-3.59],1 111 [1 048-1 178],620 [584-660],491 [460-523]
2,Australia,2020,3.74 [3.6-3.89],4.07 [3.9-4.24],3.4 [3.25-3.55],1 130 [1 089-1 174],631 [606-659],499 [477-521]
3,Australia,2019,3.75 [3.66-3.86],4.09 [3.96-4.22],3.4 [3.29-3.52],1 171 [1 140-1 203],655 [635-677],516 [498-534]
4,Australia,2018,3.76 [3.68-3.85],4.1 [3.98-4.21],3.41 [3.31-3.52],1 183 [1 156-1 210],662 [644-681],521 [505-537]
5,Australia,2017,3.78 [3.69-3.86],4.1 [3.99-4.22],3.43 [3.33-3.53],1 169 [1 143-1 195],653 [636-672],516 [501-531]
6,Australia,2016,3.81 [3.72-3.9],4.13 [4.02-4.25],3.47 [3.37-3.57],1 168 [1 141-1 195],652 [634-670],516 [502-532]
7,Australia,2015,3.87 [3.79-3.96],4.2 [4.08-4.31],3.53 [3.43-3.64],1 171 [1 145-1 197],652 [634-670],519 [504-534]

In [4]:
# Rename columns to be more descriptive
old_column0 = 'Unnamed: 0'
new_column0 = 'Countries'
old_column1 = 'Unnamed: 1'
new_column1 = 'Year'
old_column2 = 'Under-five mortality rate (per 1000 live births) (SDG 3.2.1)'
new_column2 = 'Under-five mortality rate per 1000'
old_column3 = 'Number of deaths among children under-five'
new_column3 = 'Under-five number of deaths'
df.rename(columns={old_column0: new_column0}, inplace=True)
df.rename(columns={old_column1: new_column1}, inplace=True)
df.rename(columns={old_column2: new_column2}, inplace=True)
df.rename(columns={old_column3: new_column3}, inplace=True)

# Display the updated column names
print("\nUpdated column names:")
print(df.columns)

Updated column names:
Index(['Countries', 'Year', 'Under-five mortality rate per 1000',
       'Under-five mortality rate (per 1000 live births) (SDG 3.2.1).1',
       'Under-five mortality rate (per 1000 live births) (SDG 3.2.1).2',
       'Under-five number of deaths',
       'Number of deaths among children under-five.1',
       'Number of deaths among children under-five.2'],
      dtype='object')

In [5]:
# Delete a specific row by index
my_row_index = 0
df = df.drop(my_row_index)

# Display the updated DataFrame
print("\nUpdated DataFrame:")
print(df)

Updated DataFrame:
      Countries  Year Under-five mortality rate per 1000  \
1     Australia  2021                    3.71 [3.5-3.94]
2     Australia  2020                    3.74 [3.6-3.89]
3     Australia  2019                   3.75 [3.66-3.86]
4     Australia  2018                   3.76 [3.68-3.85]
5     Australia  2017                   3.78 [3.69-3.86]
...         ...   ...                                ...
1773   Viet Nam  1968                84.32 [71.67-99.07]
1774   Viet Nam  1967                   85 [71.06-101.6]
1775   Viet Nam  1966               85.72 [70.02-104.54]
1776   Viet Nam  1965               86.32 [68.72-107.77]
1777   Viet Nam  1964                87.17 [67.1-111.58]

     Under-five mortality rate (per 1000 live births) (SDG 3.2.1).1  \
1                                       4.04 [3.8-4.29]
2                                       4.07 [3.9-4.24]
3                                      4.09 [3.96-4.22]
4                                       4.1 [3.98-4.21]
5                                       4.1 [3.99-4.22]
...                                                 ...
1773                               95.96 [81.53-113.04]
1774                                96.9 [80.85-116.17]
1775                               97.81 [79.77-119.47]
1776                               98.59 [78.16-123.26]
1777                               99.39 [76.65-127.69]

     Under-five mortality rate (per 1000 live births) (SDG 3.2.1).2  \
1                                      3.37 [3.16-3.59]
2                                       3.4 [3.25-3.55]
3                                       3.4 [3.29-3.52]
4                                      3.41 [3.31-3.52]
5                                      3.43 [3.33-3.53]
...                                                 ...
1773                                72.04 [60.93-84.98]
1774                                 72.5 [60.24-86.85]
1775                                 72.98 [59.27-89.2]
1776                                73.56 [58.23-92.01]
1777                                74.26 [56.96-95.25]

     Under-five number of deaths Number of deaths among children under-five.1  \
1            1 111 [1 048-1 178]                                620 [584-660]
2            1 130 [1 089-1 174]                                631 [606-659]
3            1 171 [1 140-1 203]                                655 [635-677]
4            1 183 [1 156-1 210]                                662 [644-681]
5            1 169 [1 143-1 195]                                653 [636-672]
...                          ...                                          ...
1773                         NaN                                          NaN
1774                         NaN                                          NaN
1775                         NaN                                          NaN
1776                         NaN                                          NaN
1777                         NaN                                          NaN

     Number of deaths among children under-five.2
1                                   491 [460-523]
2                                   499 [477-521]
3                                   516 [498-534]
4                                   521 [505-537]
5                                   516 [501-531]
...                                           ...
1773                                          NaN
1774                                          NaN
1775                                          NaN
1776                                          NaN
1777                                          NaN

[1777 rows x 8 columns]

In [6]:
## Handpicking the columns we want to keep
## For each year, we want the rate of under-five children mortality, per country
our_columns = ['Countries', 'Year', 'Under-five mortality rate per 1000']
df[our_columns]
## Example:  Dataframe shape change from [3054 rows x 8 columns] to [3054 rows × 3 columns]

      Countries  Year Under-five mortality rate per 1000
1     Australia  2021                    3.71 [3.5-3.94]
2     Australia  2020                    3.74 [3.6-3.89]
3     Australia  2019                   3.75 [3.66-3.86]
4     Australia  2018                   3.76 [3.68-3.85]
5     Australia  2017                   3.78 [3.69-3.86]
...         ...   ...                                ...
1773   Viet Nam  1968                84.32 [71.67-99.07]
1774   Viet Nam  1967                   85 [71.06-101.6]
1775   Viet Nam  1966               85.72 [70.02-104.54]
1776   Viet Nam  1965               86.32 [68.72-107.77]
1777   Viet Nam  1964                87.17 [67.1-111.58]

[1777 rows x 3 columns]

In [7]:
## Pivot the DataFrame so that the second dataframe has the same shape as the first one

# Pivot the DataFrame
df_pivot = df.pivot(index='Countries', columns='Year', values='Under-five mortality rate per 1000')
# Reset the index and rename the columns
df_pivot = df_pivot.reset_index().rename_axis(None, axis=1)

# Display the updated DataFrame
df_pivot.head(10)

,Countries,1940,1941,1942,1943,1944,1945,1946,1947,1948,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,Australia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.32 [4.23-4.41],4.13 [4.04-4.21],3.98 [3.89-4.07],3.87 [3.79-3.96],3.81 [3.72-3.9],3.78 [3.69-3.86],3.76 [3.68-3.85],3.75 [3.66-3.86],3.74 [3.6-3.89],3.71 [3.5-3.94]
1,Brunei Darussalam,NaN,NaN,NaN,NaN,NaN,304.72 [248.55-375.91],283.47 [240.87-335.36],263.76 [232.87-300.52],245.2 [223.36-269.85],...,9.99 [9.32-10.7],10.17 [9.51-10.89],10.38 [9.7-11.09],10.59 [9.9-11.32],10.81 [10.08-11.6],11.01 [10.18-11.95],11.23 [10.21-12.4],11.4 [10.13-12.9],11.5 [9.91-13.36],11.48 [9.6-13.74]
2,Cambodia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,37.75 [29.6-48.41],35.34 [26.2-47.82],33.38 [23.3-47.97],31.75 [20.86-48.26],30.26 [18.71-48.66],28.94 [16.98-49.28],27.83 [15.45-49.77],26.81 [14.15-50.16],25.79 [13.08-50.5],24.76 [12.19-50.61]
3,China,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,13.48 [12.7-14.3],12.48 [11.75-13.23],11.56 [10.88-12.27],10.71 [10.07-11.37],9.93 [9.35-10.54],9.22 [8.68-9.81],8.58 [8.06-9.13],7.98 [7.46-8.55],7.44 [6.85-8.07],6.93 [6.24-7.69]
4,Cook Islands,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.87 [7.2-13.51],9.49 [6.7-13.39],9.12 [6.27-13.31],8.8 [5.84-13.29],8.5 [5.46-13.3],8.19 [5.11-13.29],7.91 [4.77-13.29],7.64 [4.47-13.31],7.39 [4.19-13.34],7.17 [3.93-13.36]
5,Fiji,146.54 [110-200.73],145.16 [113.6-190.94],143.64 [116.49-182.19],142.15 [118.86-174.95],140.52 [120.55-168.45],139.1 [121.36-162.99],137.36 [121.14-158.2],135.28 [120.52-154.23],132.73 [119.23-149.98],...,23.65 [22.61-24.76],23.77 [22.61-25.02],24.06 [22.8-25.4],24.48 [23.18-25.86],25 [23.73-26.34],25.61 [24.39-26.89],26.27 [25-27.62],26.94 [25.35-28.62],27.48 [25.33-29.77],27.73 [24.82-30.88]
6,Japan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.01 [2.95-3.07],2.92 [2.86-2.98],2.84 [2.78-2.89],2.76 [2.71-2.81],2.69 [2.64-2.74],2.62 [2.57-2.67],2.54 [2.5-2.59],2.47 [2.42-2.52],2.39 [2.34-2.44],2.3 [2.23-2.37]
7,Kiribati,NaN,NaN,NaN,NaN,NaN,NaN,221.88 [164.44-303.8],221.43 [170.76-290.36],220.99 [176.51-278.35],...,62.08 [45.9-84.14],60.66 [43.23-85.32],59.07 [40.43-86.47],57.54 [37.89-87.18],56.09 [35.42-88.01],54.43 [33.23-88.97],52.86 [31.11-89.74],51.36 [29.14-89.64],49.8 [27.26-89.87],48.23 [25.53-89.72]
8,Lao People's Democratic Republic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,61.97 [52.96-71.93],59.02 [49.69-69.5],56.22 [46.45-67.15],53.74 [43.55-64.9],51.49 [40.85-63.3],49.39 [38.37-62.08],47.5 [35.94-61.41],45.8 [33.62-60.68],44.13 [31.35-60.45],42.51 [29.16-60.59]
9,Malaysia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.06 [7.91-8.22],8.08 [7.92-8.23],8.12 [7.96-8.28],8.16 [7.98-8.34],8.16 [7.94-8.37],8.11 [7.83-8.39],8.01 [7.66-8.38],7.88 [7.43-8.35],7.72 [7.15-8.34],7.56 [6.84-8.35]

In [8]:
## Handpicking the columns we want to keep
## For each year, we want the total Population using at least basic drinking-water, per country
keep_columns = ['Countries', '2020', '2019', '2018', '2017', '2016', '2015', '2014', '2013', '2012', '2011', '2010', '2009', '2008', '2007', '2006', '2005', '2004', '2003', '2002', '2001', '2000']
df_pivot[keep_columns]

## Dataframe shape change from [2586 rows × 3 columns] to [39 rows × 22 columns]

,Countries,2020,2019,2018,2017,2016,2015,2014,2013,2012,...,2009,2008,2007,2006,2005,2004,2003,2002,2001,2000
0,Australia,3.74 [3.6-3.89],3.75 [3.66-3.86],3.76 [3.68-3.85],3.78 [3.69-3.86],3.81 [3.72-3.9],3.87 [3.79-3.96],3.98 [3.89-4.07],4.13 [4.04-4.21],4.32 [4.23-4.41],...,5 [4.9-5.1],5.22 [5.12-5.32],5.42 [5.31-5.53],5.58 [5.48-5.7],5.72 [5.61-5.83],5.83 [5.71-5.94],5.91 [5.79-6.02],5.99 [5.87-6.1],6.08 [5.96-6.2],6.19 [6.07-6.31]
1,Brunei Darussalam,11.5 [9.91-13.36],11.4 [10.13-12.9],11.23 [10.21-12.4],11.01 [10.18-11.95],10.81 [10.08-11.6],10.59 [9.9-11.32],10.38 [9.7-11.09],10.17 [9.51-10.89],9.99 [9.32-10.7],...,9.58 [8.94-10.28],9.51 [8.88-10.2],9.47 [8.84-10.16],9.46 [8.84-10.14],9.49 [8.87-10.15],9.55 [8.94-10.21],9.65 [9.05-10.33],9.82 [9.2-10.51],10.04 [9.41-10.73],10.33 [9.68-11.03]
2,Cambodia,25.79 [13.08-50.5],26.81 [14.15-50.16],27.83 [15.45-49.77],28.94 [16.98-49.28],30.26 [18.71-48.66],31.75 [20.86-48.26],33.38 [23.3-47.97],35.34 [26.2-47.82],37.75 [29.6-48.41],...,47.55 [40.7-55.57],51.35 [44.57-59.32],55.33 [48.73-63.15],59.77 [53.1-67.26],64.78 [57.77-72.37],70.83 [63.49-78.7],78.23 [70.69-86.2],86.92 [79.31-95.1],96.86 [88.88-105.28],106.3 [97.38-115.53]
3,China,7.44 [6.85-8.07],7.98 [7.46-8.55],8.58 [8.06-9.13],9.22 [8.68-9.81],9.93 [9.35-10.54],10.71 [10.07-11.37],11.56 [10.88-12.27],12.48 [11.75-13.23],13.48 [12.7-14.3],...,17.05 [16.05-18.08],18.49 [17.38-19.6],20.11 [18.86-21.33],21.95 [20.63-23.26],24.02 [22.59-25.44],26.34 [24.85-27.89],28.86 [27.29-30.6],31.48 [29.77-33.41],34.11 [32.26-36.23],36.68 [34.71-38.92]
4,Cook Islands,7.39 [4.19-13.34],7.64 [4.47-13.31],7.91 [4.77-13.29],8.19 [5.11-13.29],8.5 [5.46-13.3],8.8 [5.84-13.29],9.12 [6.27-13.31],9.49 [6.7-13.39],9.87 [7.2-13.51],...,11.29 [8.94-14.24],11.9 [9.66-14.67],12.58 [10.41-15.19],13.29 [11.22-15.79],14.03 [12-16.45],14.79 [12.78-17.12],15.57 [13.6-17.86],16.35 [14.4-18.64],17.17 [15.2-19.44],18 [16.01-20.26]
5,Fiji,27.48 [25.33-29.77],26.94 [25.35-28.62],26.27 [25-27.62],25.61 [24.39-26.89],25 [23.73-26.34],24.48 [23.18-25.86],24.06 [22.8-25.4],23.77 [22.61-25.02],23.65 [22.61-24.76],...,23.81 [23.01-24.66],23.85 [23.07-24.66],23.76 [22.99-24.53],23.55 [22.79-24.31],23.27 [22.51-24.03],22.96 [22.2-23.72],22.7 [21.92-23.47],22.54 [21.74-23.36],22.51 [21.62-23.44],22.58 [21.53-23.71]
6,Japan,2.39 [2.34-2.44],2.47 [2.42-2.52],2.54 [2.5-2.59],2.62 [2.57-2.67],2.69 [2.64-2.74],2.76 [2.71-2.81],2.84 [2.78-2.89],2.92 [2.86-2.98],3.01 [2.95-3.07],...,3.3 [3.24-3.37],3.41 [3.35-3.48],3.52 [3.45-3.59],3.63 [3.57-3.7],3.74 [3.68-3.82],3.86 [3.79-3.93],3.99 [3.92-4.06],4.13 [4.06-4.21],4.31 [4.23-4.39],4.51 [4.42-4.59]
7,Kiribati,49.8 [27.26-89.87],51.36 [29.14-89.64],52.86 [31.11-89.74],54.43 [33.23-88.97],56.09 [35.42-88.01],57.54 [37.89-87.18],59.07 [40.43-86.47],60.66 [43.23-85.32],62.08 [45.9-84.14],...,65.13 [52.7-80.77],65.4 [54.1-79.33],65.21 [55.06-77.66],64.83 [55.37-76.08],64.46 [55.51-74.87],64.32 [55.86-74.08],64.57 [56.33-73.8],65.26 [57.27-74.2],66.37 [58.48-75.18],67.87 [59.93-76.67]
8,Lao People's Democratic Republic,44.13 [31.35-60.45],45.8 [33.62-60.68],47.5 [35.94-61.41],49.39 [38.37-62.08],51.49 [40.85-63.3],53.74 [43.55-64.9],56.22 [46.45-67.15],59.02 [49.69-69.5],61.97 [52.96-71.93],...,71.7 [63.53-80.81],75.25 [67.24-84.13],78.97 [71.05-87.82],82.86 [74.83-91.74],86.8 [78.71-95.69],90.81 [82.55-99.95],94.88 [86.52-104.29],98.96 [90.44-108.59],103.13 [94.34-112.88],107.28 [98.29-117.31]
9,Malaysia,7.72 [7.15-8.34],7.88 [7.43-8.35],8.01 [7.66-8.38],8.11 [7.83-8.39],8.16 [7.94-8.37],8.16 [7.98-8.34],8.12 [7.96-8.28],8.08 [7.92-8.23],8.06 [7.91-8.22],...,8.15 [7.99-8.31],8.13 [7.98-8.29],8.13 [7.97-8.28],8.15 [7.99-8.3],8.21 [8.05-8.37],8.32 [8.17-8.48],8.53 [8.37-8.7],8.9 [8.73-9.07],9.46 [9.28-9.64],10.16 [9.96-10.36]
10,Marshall Islands,30.72 [18.74-51.02],31.76 [20.01-50.77],32.73 [21.31-50.5],33.61 [22.69-50.27],34.58 [24.21-49.69],35.51 [25.82-49.46],36.39 [27.37-49.19],37.25 [28.97-48.73],38.02 [30.44-48.33],...,39.55 [33.68-46.73],39.92 [34.28-46.75],40.3 [34.76-46.95],40.71 [35.08-47.41],41.11 [35.37-47.93],41.45 [35.6-48.39],41.81 [35.8-48.8],42.01 [35.94-49.11],42.11 [36.09-49.37],42.06 [36.01-49.22]
11,Micronesia (Federated States of),25.64 [11.87-54.63],26.4 [12.58-54.65],27.34 [13.37-54.87],28.21 [14.15-54.92],29.23 [15.05-55.53],30.17 [15.94-55.75],31.09 [16.92-55.81],32.03 [17.85-55.69],33.03 [18.84-55.45],...,35.09 [21.86-54.03],35.59 [22.9-53.44],35.91 [23.73-52.22],35.97 [24.56-51],36.01 [25.52-49.67],36.07 [26.42-48.8],36.31 [27.31-48.31],41.43 [31.84-54.16],37.52 [29.42-48.3],38.46 [30.61-48.89]
12,Mongolia,15.35 [14.57-16.23],16.04 [15.49-16.61],16.79 [16.38-17.2],17.61 [17.25-17.99],18.5 [18.13-18.9],19.43 [19.04-19.83],20.38 [20-20.79],21.45 [21.04-21.88],22.76 [22.32-23.22],...,28.56 [27.5-29.68],31.19 [29.61-32.79],34.14 [32.06-36.29],37.43 [34.74-40.14],41.01 [37.79-44.3],44.93 [41.22-48.75],49.19 [45.03-53.53],53.79 [49.21-58.54],58.64 [53.7-63.76],63.64 [58.28-69.13]
13,Nauru,28.58 [14.92-53.24],29.57 [15.91-53.13],30.5 [16.89-53.28],31.43 [17.95-53.07],32.35 [19.04-52.96],33.3 [20.14-52.65],34.22 [21.37-52.18],35.13 [22.76-51.73],36.04 [24.19-51.46],...,38.07 [28.09-49.67],38.26 [29.25-48.63],38.24 [30.4-47.52],38.31 [31.31-46.57],38.44 [32.16-45.7],38.81 [33.02-45.44],39.41 [33.98-45.61],40.29 [34.91-46.38],41.38 [36.01-47.51],42.65 [37.09-49.07]
14,New Zealand,4.83 [4.46-5.21],4.93 [4.63-5.25],5.05 [4.78-5.33],5.19 [4.94-5.44],5.34 [5.12-5.57],5.5 [5.31-5.72],5.67 [5.48-5.88],5.84 [5.65-6.04],5.99 [5.79-6.2],...,6.32 [6.12-6.52],6.39 [6.19-6.59],6.46 [6.26-6.66],6.54 [6.33-6.74],6.63 [6.42-6.85],6.75 [6.53-6.96],6.89 [6.67-7.1],7.04 [6.82-7.26],7.2 [6.98-7.43],7.39 [7.16-7.62]
15,Niue,24.96 [10.83-58.07],25.76 [11.46-58.38],26.59 [12.18-58.64],27.41 [12.91-58.66],28.23 [13.69-59.09],29.02 [14.47-59.4],29.99 [15.22-59.57],30.9 [16.12-60.17],31.88 [16.98-59.73],...,34.37 [19.89-58.85],35.06 [20.81-58.46],35.55 [21.78-57.64],35.81 [22.63-56.63],35.88 [23.52-54.95],35.47 [24.09-52.84],34.91 [24.52-50.2],34.15 [24.73-47.47],33.24 [24.85-44.84],32.31 [24.72-42.58]
16,Palau,16.81 [8.26-34.74],17.37 [8.76-34.8],17.92 [9.29-34.83],18.52 [9.83-34.74],19.13 [10.48-34.88],19.74 [11.08-35],20.43 [11.82-35.22],21.12 [12.66-35.23],21.79 [13.5-35.27],...,23.67 [16.12-34.85],24.33 [17.07-34.63],24.93 [18.08-34.39],25.42 [19.07-33.86],25.94 [20.06-33.31],26.44 [21.05-32.93],26.9 [21.96-32.69],27.41 [22.76-32.71],27.91 [23.55-32.93],28.47 [24.23-33.29]
17,Papua New Guinea,44.17 [30.77-63.13],45.52 [32.76-63.15],46.89 [34.69-62.99],48.31 [36.67-63.05],49.74 [38.84-63.44],51.09 [41.01-64.06],52.47 [42.82-64.81],53.84 [44.65-65.67],55.19 [46.37-66.53],...,59.42 [51.28-69.39],60.85 [52.91-70.45],62.28 [54.5-71.58],63.65 [55.91-72.79],64.98 [57.34-74],66.3 [58.75-75.11],67.56 [60.1-76.17],68.75 [61.44-77.27],69.96 [62.8-78.3],71.14 [64.05-79.3]
18,Philippines,26.5 [19.36-36.25],27.28 [20.58-36.06],28.02 [21.84-35.9],28.69 [23.02-35.66],29.29 [24.11-35.47],29.78 [25.16-35.28],30.21 [26.07-35.05],30.59 [26.89-34.88],31 [27.6-34.84],...,32.17 [29.32-35.41],32.62 [29.81-35.75],33.09 [30.37-36.15],33.63 [30.91-36.65],34.23 [31.51-37.22],34.88 [32.16-37.82],35.56 [32.86-38.5],36.26 [33.57-39.18],36.97 [34.28-39.86],37.71 [35-40.62]
19,Republic of Korea,3.01 [2.92-3.1],3.12 [3.05-3.2],3.23 [3.16-3.3],3.33 [3.26-3.41],3.42 [3.36-3.5],3.52 [3.45-3.59],3.62 [3.55-3.69],3.73 [3.66-3.8],3.85 [3.77-3.92],...,4.31 [4.23-4.39],4.54 [4.45-4.62],4.83 [4.73-4.92],5.18 [5.08-5.28],5.57 [5.46-5.68],5.98 [5.86-6.1],6.39 [6.26-6.51],6.77 [6.63-6.93],7.15 [6.96-7.33],7.53 [7.28-7.78]
20,Samoa,17.13 [12.32-23.79],17.53 [13.04-23.59],17.89 [13.71-23.32],18.2 [14.35-23.04],18.4 [14.91-22.68],18.59 [15.45-22.35],18.78 [15.93-22.19],18.96 [16.3-22.08],19.13 [16.63-22.08],...,25.69 [22.63-29.1],19.36 [17.09-21.9],19.3 [17.08-21.8],19.26 [17.04-21.76],19.29 [17.04-21.84],19.42 [17.14-21.96],19.68 [17.37-22.23],20.07 [17.71-22.65],20.6 [18.17-23.17],21.26 [18.76-23.82]
21,Singapore,2.23 [1.95-2.55],2.4 [2.19-2.62],2.54 [2.35-2.76],2.65 [2.46-2.87],2.71 [2.51-2.93],2.74 [2.55-2.95],2.75 [2.56-2.95],2.76 [2.57-2.96],2.78 [2.6-2.99],...,2.84 [2.65-3.04],2.85 [2.65-3.06],2.85 [2.66-3.06],2.88 [2.69-3.1],2.94 [2.75-3.15],3.04 [2.84-3.25],3.18 [2.97-3.4],3.37 [3.16-3.59],3.6 [3.38-3.83],3.87 [3.64-4.11]
22,Solomon Islands,19.39 [12.38-29.57],20.02 [13.19-29.55],20.69 [14.07-29.6],21.37 [15.02-29.56],22.08 [15.99-29.58],22.77 [16.98-29.67],23.46 [18.04-29.93],24.14 [19.08-30.18],24.89 [20.14-30.45],...,27.1 [23.18-31.69],27.76 [23.98-32.15],28.33 [24.65-32.65],28.83 [25.25-33.03],29.23 [25.7-33.33],29.54 [26.1-33.51],29.83 [26.43-33.65],30.09 [26.77-33.8],30.4 [27.11-34.05],30.77 [27.45-34.4]
23,Tonga,11.43 [6.31-19.35],11.7 [6.68-19.2],11.91 [7.07-18.86],12.1 [7.49-18.45],12.25 [7.92-17.9],12.37 [8.41-17.34],12.48 [8.92-16.8],12.59 [9.44-16.45],12.76 [9.88-16.15],...,13.44 [11.17-16.08],13.72 [11.52-16.3],14.04 [11.87-16.58],14.39 [12.22-16.89],14.75 [12.58-17.28],15.15 [12.96-17.69],15.58 [13.33-18.16],16.04 [13.73-18.67],16.51 [14.15-19.16],16.97 [14.54-19.73]
24,Tuvalu,21.93 [12.76-37.58],22.68 [13.62-37.6],23.57 [14.55-37.74],24.34 [15.61-37.57],25.26 [16.82-37.31],26.1 [18.11-37.2],27.08 [19.52-37.14],28 [21.06-37],29.02 [22.5-37.13],...,32.66 [27.23-38.88],34.05 [28.96-39.88],35.37 [30.58-40.83],36.64 [32.07-41.76],37.78 [33.41-42.56],38.73 [34.57-43.28],39.56 [35.49-43.89],40.32 [36.3-44.67],41.15 [37.17-45.46],42.17 [38.12-46.43]
25,Vanuatu,24.01 [14.01-41.77],24.67 [14.92-41.58],25.33 [15.87-41.64],26.02 [16.74-41.51],26.68 [17.69-41.19],27.3 [18.67-40.86],27.84 [19.57-40.48],28.3 [20.45-40.03],28.59 [21.11-39.32],...,28.58 [22.76-36.26],28.53 [23.11-35.46],28.44 [23.39-34.91],28.3 [23.49-34.33],28.24 [23.58-33.99],28.24 [23.64-33.74],28.28 [23.75-33.65],28.39 [23.9-33.65],28.57 [24.12-33.86],28.85 [24.36-34.12]
26,Viet Nam,20.85 [18.92-23.04],21.06 [19.45-22.79],21.25 [19.87-22.75],21.46 [20.19-22.8],21.67 [20.46-22.94],21.89 [20.66-23.14],22.11 [20.83-23.39],22.33 [20.98-23.72],22.56 [21.08-24.08],...,23.33 [21.03-25.69],23.67 [20.99-26.34],24.07 [20.97-27.08],24.55 [21.11-27.92],25.12 [21.43-28.77],25.83 [21.84-29.67],26.66 [22.47-30.68],27.61 [23.27-31.78],28.7 [24.32-33.01],30 [25.53-34.37]

In [9]:
### Delete part after the split character "[" for all columns
final_df = df_pivot[keep_columns]
# Split columns
for column in final_df.columns:
    final_df[column] = final_df[column].str.split('[').str[0]
    
print (final_df)

                           Countries    2020    2019    2018    2017    2016  \
0                          Australia   3.74    3.75    3.76    3.78    3.81
1                  Brunei Darussalam   11.5    11.4   11.23   11.01   10.81
2                           Cambodia  25.79   26.81   27.83   28.94   30.26
3                              China   7.44    7.98    8.58    9.22    9.93
4                       Cook Islands   7.39    7.64    7.91    8.19     8.5
5                               Fiji  27.48   26.94   26.27   25.61      25
6                              Japan   2.39    2.47    2.54    2.62    2.69
7                           Kiribati   49.8   51.36   52.86   54.43   56.09
8   Lao People's Democratic Republic  44.13    45.8    47.5   49.39   51.49
9                           Malaysia   7.72    7.88    8.01    8.11    8.16
10                  Marshall Islands  30.72   31.76   32.73   33.61   34.58
11  Micronesia (Federated States of)  25.64    26.4   27.34   28.21   29.23
12                          Mongolia  15.35   16.04   16.79   17.61    18.5
13                             Nauru  28.58   29.57    30.5   31.43   32.35
14                       New Zealand   4.83    4.93    5.05    5.19    5.34
15                              Niue  24.96   25.76   26.59   27.41   28.23
16                             Palau  16.81   17.37   17.92   18.52   19.13
17                  Papua New Guinea  44.17   45.52   46.89   48.31   49.74
18                       Philippines   26.5   27.28   28.02   28.69   29.29
19                 Republic of Korea   3.01    3.12    3.23    3.33    3.42
20                             Samoa  17.13   17.53   17.89    18.2    18.4
21                         Singapore   2.23     2.4    2.54    2.65    2.71
22                   Solomon Islands  19.39   20.02   20.69   21.37   22.08
23                             Tonga  11.43    11.7   11.91    12.1   12.25
24                            Tuvalu  21.93   22.68   23.57   24.34   25.26
25                           Vanuatu  24.01   24.67   25.33   26.02   26.68
26                          Viet Nam  20.85   21.06   21.25   21.46   21.67

      2015    2014    2013    2012  ...    2009    2008    2007    2006  \
0    3.87    3.98    4.13    4.32   ...      5    5.22    5.42    5.58
1   10.59   10.38   10.17    9.99   ...   9.58    9.51    9.47    9.46
2   31.75   33.38   35.34   37.75   ...  47.55   51.35   55.33   59.77
3   10.71   11.56   12.48   13.48   ...  17.05   18.49   20.11   21.95
4     8.8    9.12    9.49    9.87   ...  11.29    11.9   12.58   13.29
5   24.48   24.06   23.77   23.65   ...  23.81   23.85   23.76   23.55
6    2.76    2.84    2.92    3.01   ...    3.3    3.41    3.52    3.63
7   57.54   59.07   60.66   62.08   ...  65.13    65.4   65.21   64.83
8   53.74   56.22   59.02   61.97   ...   71.7   75.25   78.97   82.86
9    8.16    8.12    8.08    8.06   ...   8.15    8.13    8.13    8.15
10  35.51   36.39   37.25   38.02   ...  39.55   39.92    40.3   40.71
11  30.17   31.09   32.03   33.03   ...  35.09   35.59   35.91   35.97
12  19.43   20.38   21.45   22.76   ...  28.56   31.19   34.14   37.43
13   33.3   34.22   35.13   36.04   ...  38.07   38.26   38.24   38.31
14    5.5    5.67    5.84    5.99   ...   6.32    6.39    6.46    6.54
15  29.02   29.99    30.9   31.88   ...  34.37   35.06   35.55   35.81
16  19.74   20.43   21.12   21.79   ...  23.67   24.33   24.93   25.42
17  51.09   52.47   53.84   55.19   ...  59.42   60.85   62.28   63.65
18  29.78   30.21   30.59      31   ...  32.17   32.62   33.09   33.63
19   3.52    3.62    3.73    3.85   ...   4.31    4.54    4.83    5.18
20  18.59   18.78   18.96   19.13   ...  25.69   19.36    19.3   19.26
21   2.74    2.75    2.76    2.78   ...   2.84    2.85    2.85    2.88
22  22.77   23.46   24.14   24.89   ...   27.1   27.76   28.33   28.83
23  12.37   12.48   12.59   12.76   ...  13.44   13.72   14.04   14.39
24   26.1   27.08      28   29.02   ...  32.66   34.05   35.37   36.64
25   27.3   27.84    28.3   28.59   ...  28.58   28.53   28.44    28.3
26  21.89   22.11   22.33   22.56   ...  23.33   23.67   24.07   24.55

      2005    2004    2003    2002     2001     2000
0    5.72    5.83    5.91    5.99     6.08     6.19
1    9.49    9.55    9.65    9.82    10.04    10.33
2   64.78   70.83   78.23   86.92    96.86    106.3
3   24.02   26.34   28.86   31.48    34.11    36.68
4   14.03   14.79   15.57   16.35    17.17       18
5   23.27   22.96    22.7   22.54    22.51    22.58
6    3.74    3.86    3.99    4.13     4.31     4.51
7   64.46   64.32   64.57   65.26    66.37    67.87
8    86.8   90.81   94.88   98.96   103.13   107.28
9    8.21    8.32    8.53     8.9     9.46    10.16
10  41.11   41.45   41.81   42.01    42.11    42.06
11  36.01   36.07   36.31   41.43    37.52    38.46
12  41.01   44.93   49.19   53.79    58.64    63.64
13  38.44   38.81   39.41   40.29    41.38    42.65
14   6.63    6.75    6.89    7.04      7.2     7.39
15  35.88   35.47   34.91   34.15    33.24    32.31
16  25.94   26.44    26.9   27.41    27.91    28.47
17  64.98    66.3   67.56   68.75    69.96    71.14
18  34.23   34.88   35.56   36.26    36.97    37.71
19   5.57    5.98    6.39    6.77     7.15     7.53
20  19.29   19.42   19.68   20.07     20.6    21.26
21   2.94    3.04    3.18    3.37      3.6     3.87
22  29.23   29.54   29.83   30.09     30.4    30.77
23  14.75   15.15   15.58   16.04    16.51    16.97
24  37.78   38.73   39.56   40.32    41.15    42.17
25  28.24   28.24   28.28   28.39    28.57    28.85
26  25.12   25.83   26.66   27.61     28.7       30

[27 rows x 22 columns]

C:\Users\esspe\AppData\Local\Temp\ipykernel_9348\2081836414.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df[column] = final_df[column].str.split('[').str[0]

In [10]:
## Check the dataset after all the changes
final_df.head(10)

,Countries,2020,2019,2018,2017,2016,2015,2014,2013,2012,...,2009,2008,2007,2006,2005,2004,2003,2002,2001,2000
0,Australia,3.74,3.75,3.76,3.78,3.81,3.87,3.98,4.13,4.32,...,5,5.22,5.42,5.58,5.72,5.83,5.91,5.99,6.08,6.19
1,Brunei Darussalam,11.5,11.4,11.23,11.01,10.81,10.59,10.38,10.17,9.99,...,9.58,9.51,9.47,9.46,9.49,9.55,9.65,9.82,10.04,10.33
2,Cambodia,25.79,26.81,27.83,28.94,30.26,31.75,33.38,35.34,37.75,...,47.55,51.35,55.33,59.77,64.78,70.83,78.23,86.92,96.86,106.3
3,China,7.44,7.98,8.58,9.22,9.93,10.71,11.56,12.48,13.48,...,17.05,18.49,20.11,21.95,24.02,26.34,28.86,31.48,34.11,36.68
4,Cook Islands,7.39,7.64,7.91,8.19,8.5,8.8,9.12,9.49,9.87,...,11.29,11.9,12.58,13.29,14.03,14.79,15.57,16.35,17.17,18
5,Fiji,27.48,26.94,26.27,25.61,25,24.48,24.06,23.77,23.65,...,23.81,23.85,23.76,23.55,23.27,22.96,22.7,22.54,22.51,22.58
6,Japan,2.39,2.47,2.54,2.62,2.69,2.76,2.84,2.92,3.01,...,3.3,3.41,3.52,3.63,3.74,3.86,3.99,4.13,4.31,4.51
7,Kiribati,49.8,51.36,52.86,54.43,56.09,57.54,59.07,60.66,62.08,...,65.13,65.4,65.21,64.83,64.46,64.32,64.57,65.26,66.37,67.87
8,Lao People's Democratic Republic,44.13,45.8,47.5,49.39,51.49,53.74,56.22,59.02,61.97,...,71.7,75.25,78.97,82.86,86.8,90.81,94.88,98.96,103.13,107.28
9,Malaysia,7.72,7.88,8.01,8.11,8.16,8.16,8.12,8.08,8.06,...,8.15,8.13,8.13,8.15,8.21,8.32,8.53,8.9,9.46,10.16

In [11]:
# Save the modified DataFrame to a new CSV file
final_df.to_csv('new_child_mortality_western-pacific.csv', index=False)

### Merge all all 6 datasets into one in other to have all the countries
The original datatet about mortality rate for children under five was divided into 6 WHO regions.
Now that we've cleaned the data in all 6 CSV files for each WHO region (Americas, Africa, Eastern mediterranean region, Europe, South-east Esia, Western Pacific) and saved each as a new file, let's merge all of them.

In [16]:
# Load the six datasets

df1 = pd.read_csv('child_mort_data/new_child_mortality_africa.csv')
df2 = pd.read_csv('child_mort_data/new_child_mortality_americas.csv')
df3 = pd.read_csv('child_mort_data/new_child_mortality_eastern-mediterranean.csv')
df4 = pd.read_csv('child_mort_data/new_child_mortality_europe.csv')
df5 = pd.read_csv('child_mort_data/new_child_mortality_south-east-asia.csv')
df6 = pd.read_csv('child_mort_data/new_child_mortality_western-pacific.csv')

# Combine the datasets vertically
combined_df = pd.concat([df1, df2, df3, df4, df5, df6])

# Reset the index of the combined DataFrame
combined_df = combined_df.reset_index(drop=True)

# Display the combined DataFrame
print(combined_df)
print(f"combined df shape: {combined_df.shape}")  ## combined df shape: (199, 22)

           Countries   2020   2019   2018   2017   2016    2015    2014  \
0            Algeria  22.90  23.45  23.98  24.48  24.92   25.30   25.67
1             Angola  72.07  75.04  77.97  81.08  84.45   88.34   92.91
2              Benin  86.03  88.61  91.10  93.44  95.64   97.87  100.13
3           Botswana  36.31  37.74  38.96  39.94  43.52   45.37   48.18
4       Burkina Faso  85.35  88.23  91.35  94.50  97.66  101.09  104.73
..               ...    ...    ...    ...    ...    ...     ...     ...
194  Solomon Islands  19.39  20.02  20.69  21.37  22.08   22.77   23.46
195            Tonga  11.43  11.70  11.91  12.10  12.25   12.37   12.48
196           Tuvalu  21.93  22.68  23.57  24.34  25.26   26.10   27.08
197          Vanuatu  24.01  24.67  25.33  26.02  26.68   27.30   27.84
198         Viet Nam  20.85  21.06  21.25  21.46  21.67   21.89   22.11

       2013    2012  ...    2009    2008    2007    2006    2005    2004  \
0     26.05   26.49  ...   28.71   29.77   30.98   32.34   33.78   35.30
1     98.31  104.88  ...  128.50  137.54  147.10  156.78  166.19  175.45
2    102.35  104.60  ...  111.45  113.82  116.29  118.87  121.60  124.44
3     50.31   55.22  ...   65.93   68.78   68.59   68.85   71.32   73.68
4    108.73  112.90  ...  127.22  133.05  139.34  146.04  152.79  159.15
..      ...     ...  ...     ...     ...     ...     ...     ...     ...
194   24.14   24.89  ...   27.10   27.76   28.33   28.83   29.23   29.54
195   12.59   12.76  ...   13.44   13.72   14.04   14.39   14.75   15.15
196   28.00   29.02  ...   32.66   34.05   35.37   36.64   37.78   38.73
197   28.30   28.59  ...   28.58   28.53   28.44   28.30   28.24   28.24
198   22.33   22.56  ...   23.33   23.67   24.07   24.55   25.12   25.83

       2003    2002    2001    2000
0     36.87   38.49   40.10   41.69
1    184.16  191.94  198.90  205.14
2    127.43  130.49  133.64  136.81
3     73.05   72.24   73.17   74.01
4    164.99  170.17  174.69  178.71
..      ...     ...     ...     ...
194   29.83   30.09   30.40   30.77
195   15.58   16.04   16.51   16.97
196   39.56   40.32   41.15   42.17
197   28.28   28.39   28.57   28.85
198   26.66   27.61   28.70   30.00

[199 rows x 22 columns]
combined df shape: (199, 22)

In [17]:
# Save the combined DataFrame to a new CSV file
combined_df.to_csv('child_mortality_allregions.csv', index=False)

In [12]:
## See the next Notebook