## Introduction
This notebook series propose a data preprocessing script to visualize the correlation between access to clean drinking waterand child mortality accross the world.
The dataset was downloaded from WHO open data.

### Step 1. Load and clean the first dataset about drinking water access
Check what our datasets look like and only keep the rows and columns we need, saved as a new csv file

In [3]:
## Load 1st CSV file
import pandas as pd
import numpy as np
import scipy.stats as stats

url1 = 'drinking_water.csv'
df1 = pd.read_csv(url1, delimiter=',')
print(f"df1 type: {type(df1)}")   ## df type: <class 'pandas.core.frame.DataFrame'>
print(f"df1 shape: {df1.shape}")  ## df shape: (198,127)'

df1 type: <class 'pandas.core.frame.DataFrame'>
df1 shape: (198, 127)

In [7]:
## Check the details of the dataset 
df1.info()

## DETAILS

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 198 entries, 0 to 197
Columns: 127 entries, Unnamed: 0 to 2000.5
dtypes: object(127)
memory usage: 196.6+ KB

In [8]:
## Check the fisrt rows of the dataset
df1.head(8)

,Unnamed: 0,2020,2020.1,2020.2,2020.3,2020.4,2020.5,2019,2019.1,2019.2,...,2001.2,2001.3,2001.4,2001.5,2000,2000.1,2000.2,2000.3,2000.4,2000.5
0,NaN,Population using at least basic drinking-water...,Population using at least basic drinking-water...,Population using at least basic drinking-water...,Population using safely managed drinking-water...,Population using safely managed drinking-water...,Population using safely managed drinking-water...,Population using at least basic drinking-water...,Population using at least basic drinking-water...,Population using at least basic drinking-water...,...,Population using at least basic drinking-water...,Population using safely managed drinking-water...,Population using safely managed drinking-water...,Population using safely managed drinking-water...,Population using at least basic drinking-water...,Population using at least basic drinking-water...,Population using at least basic drinking-water...,Population using safely managed drinking-water...,Population using safely managed drinking-water...,Population using safely managed drinking-water...
1,"Countries, territories and areas",Total,Urban,Rural,Total,Urban,Rural,Total,Urban,Rural,...,Rural,Total,Urban,Rural,Total,Urban,Rural,Total,Urban,Rural
2,Afghanistan,75,100,66,28,36,24,72,98,64,...,21,11,21,8,28,52,21,11,21,8
3,Albania,95,96,94,71,NaN,NaN,95,96,93,...,81,49,NaN,NaN,87,96,80,49,NaN,NaN
4,Algeria,94,96,90,72,74,69,94,96,90,...,84,71,82,53,90,94,83,70,82,52
5,Andorra,100,100,100,91,NaN,NaN,100,100,100,...,100,91,NaN,NaN,100,100,100,91,NaN,NaN
6,Angola,57,72,28,NaN,NaN,NaN,57,72,28,...,22,NaN,NaN,NaN,41,61,21,NaN,NaN,NaN
7,Antigua and Barbuda,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,98,NaN,NaN,NaN,NaN,NaN

In [9]:
df1.columns

Index(['Unnamed: 0', '2020', '2020.1', '2020.2', '2020.3', '2020.4', '2020.5',
       '2019', '2019.1', '2019.2',
       ...
       '2001.2', '2001.3', '2001.4', '2001.5', '2000', '2000.1', '2000.2',
       '2000.3', '2000.4', '2000.5'],
      dtype='object', length=127)

In [11]:
# Rename columns to be more descriptive
old_column_name = 'Unnamed: 0'
new_column_name = 'Countries'
df1.rename(columns={old_column_name: new_column_name}, inplace=True)

# Display the updated column names
print("\nUpdated column names:")
print(df1.columns)

Updated column names:
Index(['Countries', '2020', '2020.1', '2020.2', '2020.3', '2020.4', '2020.5',
       '2019', '2019.1', '2019.2',
       ...
       '2001.2', '2001.3', '2001.4', '2001.5', '2000', '2000.1', '2000.2',
       '2000.3', '2000.4', '2000.5'],
      dtype='object', length=127)

In [14]:
# Delete a specific row by index
row_index = 0
df1 = df1.drop(row_index)

# Display the updated DataFrame
print("\nUpdated DataFrame:")
print(df1)

Updated DataFrame:
                              Countries   2020 2020.1 2020.2 2020.3 2020.4  \
1      Countries, territories and areas  Total  Urban  Rural  Total  Urban
2                           Afghanistan     75    100     66     28     36
3                               Albania     95     96     94     71    NaN
4                               Algeria     94     96     90     72     74
5                               Andorra    100    100    100     91    NaN
..                                  ...    ...    ...    ...    ...    ...
193  Venezuela (Bolivarian Republic of)     94    NaN    NaN    NaN    NaN
194                            Viet Nam     97     99     96    NaN    NaN
195                               Yemen     61     77     51    NaN    NaN
196                              Zambia     65     87     48    NaN     50
197                            Zimbabwe     63     93     48     30     65

    2020.5   2019 2019.1 2019.2  ... 2001.2 2001.3 2001.4 2001.5   2000  \
1    Rural  Total  Urban  Rural  ...  Rural  Total  Urban  Rural  Total
2       24     72     98     64  ...     21     11     21      8     28
3      NaN     95     96     93  ...     81     49    NaN    NaN     87
4       69     94     96     90  ...     84     71     82     53     90
5      NaN    100    100    100  ...    100     91    NaN    NaN    100
..     ...    ...    ...    ...  ...    ...    ...    ...    ...    ...
193    NaN     94    NaN    NaN  ...    NaN    NaN    NaN    NaN     97
194    NaN     96     99     95  ...     77    NaN    NaN    NaN     81
195    NaN     60     77     50  ...     29    NaN    NaN    NaN     41
196    NaN     65     87     47  ...     30    NaN     45    NaN     48
197     13     63     93     49  ...     60     33     64     17     72

    2000.1 2000.2 2000.3 2000.4 2000.5
1    Urban  Rural  Total  Urban  Rural
2       52     21     11     21      8
3       96     80     49    NaN    NaN
4       94     83     70     82     52
5      100    100     91    NaN    NaN
..     ...    ...    ...    ...    ...
193    NaN    NaN    NaN    NaN    NaN
194     95     76    NaN    NaN    NaN
195     74     29    NaN    NaN    NaN
196     83     29    NaN     44    NaN
197     95     60     33     64     17

[197 rows x 127 columns]

In [19]:
# Delete a specific row by index
row_index1 = 1
df1 = df1.drop(row_index1)

# Display the updated DataFrame
print("\nUpdated DataFrame:")
print(df1)

Updated DataFrame:
                              Countries 2020 2020.1 2020.2 2020.3 2020.4  \
2                           Afghanistan   75    100     66     28     36
3                               Albania   95     96     94     71    NaN
4                               Algeria   94     96     90     72     74
5                               Andorra  100    100    100     91    NaN
6                                Angola   57     72     28    NaN    NaN
..                                  ...  ...    ...    ...    ...    ...
193  Venezuela (Bolivarian Republic of)   94    NaN    NaN    NaN    NaN
194                            Viet Nam   97     99     96    NaN    NaN
195                               Yemen   61     77     51    NaN    NaN
196                              Zambia   65     87     48    NaN     50
197                            Zimbabwe   63     93     48     30     65

    2020.5 2019 2019.1 2019.2  ... 2001.2 2001.3 2001.4 2001.5 2000 2000.1  \
2       24   72     98     64  ...     21     11     21      8   28     52
3      NaN   95     96     93  ...     81     49    NaN    NaN   87     96
4       69   94     96     90  ...     84     71     82     53   90     94
5      NaN  100    100    100  ...    100     91    NaN    NaN  100    100
6      NaN   57     72     28  ...     22    NaN    NaN    NaN   41     61
..     ...  ...    ...    ...  ...    ...    ...    ...    ...  ...    ...
193    NaN   94    NaN    NaN  ...    NaN    NaN    NaN    NaN   97    NaN
194    NaN   96     99     95  ...     77    NaN    NaN    NaN   81     95
195    NaN   60     77     50  ...     29    NaN    NaN    NaN   41     74
196    NaN   65     87     47  ...     30    NaN     45    NaN   48     83
197     13   63     93     49  ...     60     33     64     17   72     95

    2000.2 2000.3 2000.4 2000.5
2       21     11     21      8
3       80     49    NaN    NaN
4       83     70     82     52
5      100     91    NaN    NaN
6       21    NaN    NaN    NaN
..     ...    ...    ...    ...
193    NaN    NaN    NaN    NaN
194     76    NaN    NaN    NaN
195     29    NaN    NaN    NaN
196     29    NaN     44    NaN
197     60     33     64     17

[196 rows x 127 columns]

In [20]:
## Handpicking the columns we want to keep
## For each year, we want the total Population using at least basic drinking-water, per country
my_columns = ['Countries', '2020', '2019', '2018', '2017', '2016', '2015', '2014', '2013', '2012', '2011', '2010', '2009', '2008', '2007', '2006', '2005', '2004', '2003', '2002', '2001', '2000']
df1[my_columns]

## Dataframe shape change from [197 rows x 127 columns] to [197 rows × 22 columns]

,Countries,2020,2019,2018,2017,2016,2015,2014,2013,2012,...,2009,2008,2007,2006,2005,2004,2003,2002,2001,2000
2,Afghanistan,75,72,70,67,64,61,59,56,53,...,46,43,41,38,36,34,32,30,28,28
3,Albania,95,95,94,94,94,93,93,93,92,...,91,90,90,90,89,89,88,87,87,87
4,Algeria,94,94,94,94,94,93,93,93,93,...,92,92,92,91,91,91,91,90,90,90
5,Andorra,100,100,100,100,100,100,100,100,100,...,100,100,100,100,100,100,100,100,100,100
6,Angola,57,57,57,56,55,54,54,53,52,...,50,49,48,47,46,45,44,43,42,41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193,Venezuela (Bolivarian Republic of),94,94,94,94,94,95,95,95,95,...,96,96,96,96,96,97,97,97,97,97
194,Viet Nam,97,96,96,95,94,93,92,91,90,...,88,87,86,86,85,84,83,82,81,81
195,Yemen,61,60,59,58,57,56,55,54,53,...,49,48,47,46,45,44,43,41,41,41
196,Zambia,65,65,64,63,62,61,61,60,59,...,56,55,54,54,53,52,51,50,49,48
197,Zimbabwe,63,63,64,64,64,65,65,66,66,...,68,69,69,70,70,71,71,72,72,72

In [26]:
# Save the modified DataFrame to a new CSV file
# df1[my_columns].to_csv('new_drinking_water.csv', index=False)

### Step 2 - Load and clean the second dataset about mortality for children under-five
The original data is separated by WHO region: Region of the Americas, African region, Eastern mediterranean region, European region, South-east asian region, Western pacific region. We will preprocess the data one region at a time, starting with the Region of the Americas

In [41]:
## Load 2nd CSV file containing data for Region of the Americas

url2 = 'child_mortality_americas.csv'
df2 = pd.read_csv(url2, delimiter=',')
print(f"df2 type: {type(df2)}")   ## df type: <class 'pandas.core.frame.DataFrame'>
print(f"df2 shape: {df2.shape}")  ## df shape: (2587, 8)'

df2 type: <class 'pandas.core.frame.DataFrame'>
df2 shape: (2587, 8)

In [42]:
## Check the details of the dataset 
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2587 entries, 0 to 2586
Data columns (total 8 columns):
 #   Column                                                          Non-Null Count  Dtype
---  ------                                                          --------------  -----
 0   Unnamed: 0                                                      2587 non-null   object
 1   Unnamed: 1                                                      2587 non-null   object
 2   Under-five mortality rate (per 1000 live births) (SDG 3.2.1)    2587 non-null   object
 3   Under-five mortality rate (per 1000 live births) (SDG 3.2.1).1  2561 non-null   object
 4   Under-five mortality rate (per 1000 live births) (SDG 3.2.1).2  2561 non-null   object
 5   Number of deaths among children under-five                      2366 non-null   object
 6   Number of deaths among children under-five.1                    2366 non-null   object
 7   Number of deaths among children under-five.2                    2366 non-null   object
dtypes: object(8)
memory usage: 161.8+ KB

In [43]:
## Check the fisrt rows of the dataset
df2.head(8)

,Unnamed: 0,Unnamed: 1,Under-five mortality rate (per 1000 live births) (SDG 3.2.1),Under-five mortality rate (per 1000 live births) (SDG 3.2.1).1,Under-five mortality rate (per 1000 live births) (SDG 3.2.1).2,Number of deaths among children under-five,Number of deaths among children under-five.1,Number of deaths among children under-five.2
0,"Countries, territories and areas",Year,Both sexes,Male,Female,Both sexes,Male,Female
1,British Virgin Islands,2021,10.46 [4.75-22.78],11.35 [5.15-24.98],9.49 [4.31-20.63],2 [1-5],1 [1-3],1 [0-2]
2,British Virgin Islands,2020,10.85 [5.05-22.86],11.73 [5.49-24.99],9.85 [4.59-20.78],2 [1-5],1 [1-3],1 [1-2]
3,British Virgin Islands,2019,11.18 [5.39-22.97],12.16 [5.86-25.04],10.14 [4.87-20.86],2 [1-5],1 [1-3],1 [1-2]
4,British Virgin Islands,2018,11.55 [5.71-23.09],12.55 [6.24-25.18],10.49 [5.19-21.02],2 [1-5],1 [1-3],1 [1-2]
5,British Virgin Islands,2017,11.89 [6.05-23.36],12.94 [6.57-25.36],10.86 [5.5-21.29],3 [1-5],1 [1-3],2 [1-2]
6,British Virgin Islands,2016,12.29 [6.4-23.42],13.37 [6.94-25.52],11.15 [5.82-21.38],3 [2-6],2 [1-3],1 [1-3]
7,British Virgin Islands,2015,12.69 [6.82-23.42],13.77 [7.38-25.51],11.51 [6.19-21.36],3 [2-6],2 [1-4],1 [1-3]

In [44]:
# Rename columns to be more descriptive
old_column0 = 'Unnamed: 0'
new_column0 = 'Countries'
old_column1 = 'Unnamed: 1'
new_column1 = 'Year'
old_column2 = 'Under-five mortality rate (per 1000 live births) (SDG 3.2.1)'
new_column2 = 'Under-five mortality rate per 1000'
old_column3 = 'Number of deaths among children under-five'
new_column3 = 'Under-five number of deaths'
df2.rename(columns={old_column0: new_column0}, inplace=True)
df2.rename(columns={old_column1: new_column1}, inplace=True)
df2.rename(columns={old_column2: new_column2}, inplace=True)
df2.rename(columns={old_column3: new_column3}, inplace=True)

# Display the updated column names
print("\nUpdated column names:")
print(df2.columns)

Updated column names:
Index(['Countries', 'Year', 'Under-five mortality rate per 1000',
       'Under-five mortality rate (per 1000 live births) (SDG 3.2.1).1',
       'Under-five mortality rate (per 1000 live births) (SDG 3.2.1).2',
       'Under-five number of deaths',
       'Number of deaths among children under-five.1',
       'Number of deaths among children under-five.2'],
      dtype='object')

In [45]:
# Delete a specific row by index
my_row_index = 0
df2 = df2.drop(my_row_index)

# Display the updated DataFrame
print("\nUpdated DataFrame:")
print(df2)

Updated DataFrame:
                               Countries  Year  \
1                 British Virgin Islands  2021
2                 British Virgin Islands  2020
3                 British Virgin Islands  2019
4                 British Virgin Islands  2018
5                 British Virgin Islands  2017
...                                  ...   ...
2582  Venezuela (Bolivarian Republic of)  1955
2583  Venezuela (Bolivarian Republic of)  1954
2584  Venezuela (Bolivarian Republic of)  1953
2585  Venezuela (Bolivarian Republic of)  1952
2586  Venezuela (Bolivarian Republic of)  1951

     Under-five mortality rate per 1000  \
1                    10.46 [4.75-22.78]
2                    10.85 [5.05-22.86]
3                    11.18 [5.39-22.97]
4                    11.55 [5.71-23.09]
5                    11.89 [6.05-23.36]
...                                 ...
2582                97.5 [78.45-122.21]
2583              101.92 [79.64-132.42]
2584              106.68 [80.47-143.83]
2585              111.61 [80.98-157.68]
2586                 116.89 [81-172.28]

     Under-five mortality rate (per 1000 live births) (SDG 3.2.1).1  \
1                                    11.35 [5.15-24.98]
2                                    11.73 [5.49-24.99]
3                                    12.16 [5.86-25.04]
4                                    12.55 [6.24-25.18]
5                                    12.94 [6.57-25.36]
...                                                 ...
2582                               104.1 [83.58-131.09]
2583                              108.54 [84.61-141.42]
2584                                113.5 [85.43-153.5]
2585                              118.71 [85.76-167.74]
2586                              123.73 [85.53-183.73]

     Under-five mortality rate (per 1000 live births) (SDG 3.2.1).2  \
1                                     9.49 [4.31-20.63]
2                                     9.85 [4.59-20.78]
3                                    10.14 [4.87-20.86]
4                                    10.49 [5.19-21.02]
5                                     10.86 [5.5-21.29]
...                                                 ...
2582                               90.74 [72.86-113.94]
2583                                95.02 [73.8-123.47]
2584                               99.53 [74.92-134.46]
2585                               104.4 [75.52-146.79]
2586                               109.41 [75.67-160.9]

     Under-five number of deaths Number of deaths among children under-five.1  \
1                        2 [1-5]                                      1 [1-3]
2                        2 [1-5]                                      1 [1-3]
3                        2 [1-5]                                      1 [1-3]
4                        2 [1-5]                                      1 [1-3]
5                        3 [1-5]                                      1 [1-3]
...                          ...                                          ...
2582                         NaN                                          NaN
2583                         NaN                                          NaN
2584                         NaN                                          NaN
2585                         NaN                                          NaN
2586                         NaN                                          NaN

     Number of deaths among children under-five.2
1                                         1 [0-2]
2                                         1 [1-2]
3                                         1 [1-2]
4                                         1 [1-2]
5                                         2 [1-2]
...                                           ...
2582                                          NaN
2583                                          NaN
2584                                          NaN
2585                                          NaN
2586                                          NaN

[2586 rows x 8 columns]

In [46]:
## Handpicking the columns we want to keep
## For each year, we want the rate of under-five children mortality, per country
our_columns = ['Countries', 'Year', 'Under-five mortality rate per 1000']
df2[our_columns]
## Dataframe shape change from [2586 rows x 8 columns] to [2586 rows × 3 columns]

,Countries,Year,Under-five mortality rate per 1000
1,British Virgin Islands,2021,10.46 [4.75-22.78]
2,British Virgin Islands,2020,10.85 [5.05-22.86]
3,British Virgin Islands,2019,11.18 [5.39-22.97]
4,British Virgin Islands,2018,11.55 [5.71-23.09]
5,British Virgin Islands,2017,11.89 [6.05-23.36]
...,...,...,...
2582,Venezuela (Bolivarian Republic of),1955,97.5 [78.45-122.21]
2583,Venezuela (Bolivarian Republic of),1954,101.92 [79.64-132.42]
2584,Venezuela (Bolivarian Republic of),1953,106.68 [80.47-143.83]
2585,Venezuela (Bolivarian Republic of),1952,111.61 [80.98-157.68]
2586,Venezuela (Bolivarian Republic of),1951,116.89 [81-172.28]

In [47]:
## Pivot the DataFrame so that the second dataframe has the same shape as the first one

# Pivot the DataFrame
df2_pivot = df2.pivot(index='Countries', columns='Year', values='Under-five mortality rate per 1000')
# Reset the index and rename the columns
df2_pivot = df2_pivot.reset_index().rename_axis(None, axis=1)

# Display the updated DataFrame
df2_pivot.head(10)

,Countries,1934,1935,1936,1937,1938,1939,1940,1941,1942,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,Anguilla,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.55 [3.31-9.42],5.33 [3.09-9.28],5.14 [2.91-9.19],4.97 [2.72-9.1],4.8 [2.56-9.08],4.64 [2.41-8.96],4.49 [2.27-8.83],4.33 [2.13-8.72],4.18 [2.03-8.62],4.05 [1.92-8.52]
1,Antigua and Barbuda,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.02 [7.78-10.43],8.55 [7.23-10.06],8.13 [6.72-9.78],7.75 [6.24-9.59],7.43 [5.79-9.49],7.12 [5.37-9.43],6.84 [5.01-9.43],6.59 [4.65-9.43],6.36 [4.31-9.47],6.14 [4-9.52]
2,Argentina,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,13.34 [13.09-13.6],12.75 [12.51-12.99],12.17 [11.94-12.4],11.59 [11.38-11.82],10.97 [10.76-11.19],10.25 [10.06-10.46],9.45 [9.27-9.63],8.58 [8.4-8.77],7.7 [7.46-7.96],6.92 [6.58-7.29]
3,Bahamas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,14.72 [13.75-15.71],14.41 [13.44-15.41],14.15 [13.21-15.16],13.93 [13-14.95],13.76 [12.8-14.8],13.63 [12.62-14.72],13.53 [12.4-14.72],23.42 [21.09-25.89],13.32 [11.72-15.11],13.16 [11.29-15.36]
4,Barbados,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,14.74 [13.12-16.5],14.55 [12.66-16.73],14.35 [12.16-16.92],14.07 [11.53-17.12],13.77 [10.88-17.29],13.43 [10.24-17.51],13.04 [9.58-17.79],12.66 [8.98-17.97],12.29 [8.38-18.19],11.91 [7.82-18.27]
5,Belize,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,17.68 [16.75-18.64],16.93 [16.02-17.89],16.12 [15.22-17.11],15.32 [14.38-16.34],14.51 [13.43-15.65],13.73 [12.48-15.07],12.98 [11.52-14.59],12.3 [10.62-14.23],11.7 [9.79-13.93],11.19 [9.04-13.75]
6,Bolivia (Plurinational State of),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,37.3 [32.36-42.83],35.22 [30.1-41.01],33.33 [28.05-39.31],31.64 [26.13-37.92],30.2 [24.45-36.84],28.92 [22.87-36.11],27.72 [21.42-35.65],26.59 [19.97-35.33],25.63 [18.65-35.18],24.69 [17.38-35.16]
7,Brazil,266.51 [195.85-364.17],263.67 [202.16-343.62],260.95 [208.39-326.18],258.44 [212.53-313.25],255.46 [214.83-301.59],252.91 [216.39-293.95],250.12 [216.02-288.87],247.06 [213.45-286.1],244.08 [210.01-283.63],...,17.24 [16.9-17.59],16.72 [16.36-17.08],16.3 [15.87-16.74],15.95 [15.39-16.51],16.75 [15.99-17.53],15.39 [14.49-16.34],15.16 [14-16.41],14.94 [13.48-16.58],14.7 [12.91-16.75],14.41 [12.28-16.87]
8,British Virgin Islands,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,13.8 [8.08-23.45],13.44 [7.64-23.54],13.06 [7.23-23.43],12.69 [6.82-23.42],12.29 [6.4-23.42],11.89 [6.05-23.36],11.55 [5.71-23.09],11.18 [5.39-22.97],10.85 [5.05-22.86],10.46 [4.75-22.78]
9,Canada,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.58 [5.48-5.68],5.51 [5.42-5.6],5.45 [5.35-5.54],5.39 [5.29-5.48],5.33 [5.24-5.42],5.28 [5.19-5.37],5.23 [5.13-5.32],5.18 [5.06-5.29],5.11 [4.97-5.27],5.04 [4.82-5.26]

In [48]:
## Handpicking the columns we want to keep
## For each year, we want the total Population using at least basic drinking-water, per country
keep_columns = ['Countries', '2020', '2019', '2018', '2017', '2016', '2015', '2014', '2013', '2012', '2011', '2010', '2009', '2008', '2007', '2006', '2005', '2004', '2003', '2002', '2001', '2000']
df2_pivot[keep_columns]

## Dataframe shape change from [2586 rows × 3 columns] to [39 rows × 22 columns]

,Countries,2020,2019,2018,2017,2016,2015,2014,2013,2012,...,2009,2008,2007,2006,2005,2004,2003,2002,2001,2000
0,Anguilla,4.18 [2.03-8.62],4.33 [2.13-8.72],4.49 [2.27-8.83],4.64 [2.41-8.96],4.8 [2.56-9.08],4.97 [2.72-9.1],5.14 [2.91-9.19],5.33 [3.09-9.28],5.55 [3.31-9.42],...,6.34 [4.03-9.94],6.62 [4.3-10.28],6.91 [4.55-10.63],7.23 [4.78-11],7.56 [5.03-11.4],7.92 [5.28-11.88],8.31 [5.55-12.35],8.71 [5.86-12.87],9.12 [6.2-13.41],9.57 [6.57-13.97]
1,Antigua and Barbuda,6.36 [4.31-9.47],6.59 [4.65-9.43],6.84 [5.01-9.43],7.12 [5.37-9.43],7.43 [5.79-9.49],7.75 [6.24-9.59],8.13 [6.72-9.78],8.55 [7.23-10.06],9.02 [7.78-10.43],...,10.6 [9.33-12.04],11.16 [9.85-12.69],11.75 [10.4-13.3],12.34 [10.96-13.93],12.94 [11.52-14.56],13.53 [12.09-15.17],14.1 [12.65-15.79],14.65 [13.15-16.37],15.12 [13.62-16.85],15.53 [14.02-17.29]
2,Argentina,7.7 [7.46-7.96],8.58 [8.4-8.77],9.45 [9.27-9.63],10.25 [10.06-10.46],10.97 [10.76-11.19],11.59 [11.38-11.82],12.17 [11.94-12.4],12.75 [12.51-12.99],13.34 [13.09-13.6],...,14.96 [14.67-15.25],15.37 [15.08-15.66],15.72 [15.43-16.03],16.11 [15.8-16.43],16.59 [16.27-16.9],17.13 [16.8-17.46],17.72 [17.38-18.05],18.34 [17.99-18.69],18.99 [18.63-19.37],19.68 [19.3-20.04]
3,Bahamas,13.32 [11.72-15.11],23.42 [21.09-25.89],13.53 [12.4-14.72],13.63 [12.62-14.72],13.76 [12.8-14.8],13.93 [13-14.95],14.15 [13.21-15.16],14.41 [13.44-15.41],14.72 [13.75-15.71],...,15.82 [14.85-16.81],16.2 [15.21-17.23],16.53 [15.54-17.57],16.79 [15.79-17.82],16.92 [15.93-17.95],16.91 [15.93-17.95],16.79 [15.82-17.85],16.6 [15.62-17.66],16.41 [15.44-17.47],16.3 [15.33-17.35]
4,Barbados,12.29 [8.38-18.19],12.66 [8.98-17.97],13.04 [9.58-17.79],13.43 [10.24-17.51],13.77 [10.88-17.29],14.07 [11.53-17.12],14.35 [12.16-16.92],14.55 [12.66-16.73],14.74 [13.12-16.5],...,15.14 [13.99-16.4],15.31 [14.17-16.54],15.47 [14.34-16.68],15.63 [14.49-16.83],15.74 [14.62-16.93],15.78 [14.66-16.97],15.72 [14.62-16.89],15.59 [14.49-16.73],15.38 [14.31-16.51],15.16 [14.1-16.3]
5,Belize,11.7 [9.79-13.93],12.3 [10.62-14.23],12.98 [11.52-14.59],13.73 [12.48-15.07],14.51 [13.43-15.65],15.32 [14.38-16.34],16.12 [15.22-17.11],16.93 [16.02-17.89],17.68 [16.75-18.64],...,19.45 [18.48-20.44],19.88 [18.91-20.88],20.26 [19.29-21.27],20.6 [19.64-21.63],20.92 [19.94-21.97],21.28 [20.28-22.34],21.7 [20.66-22.79],22.21 [21.08-23.4],22.85 [21.59-24.2],23.61 [22.13-25.21]
6,Bolivia (Plurinational State of),25.63 [18.65-35.18],26.59 [19.97-35.33],27.72 [21.42-35.65],28.92 [22.87-36.11],30.2 [24.45-36.84],31.64 [26.13-37.92],33.33 [28.05-39.31],35.22 [30.1-41.01],37.3 [32.36-42.83],...,44.44 [39.7-49.5],47.13 [42.41-52.15],50 [45.29-54.97],53.07 [48.47-57.99],56.34 [51.82-61.19],59.79 [55.29-64.62],63.46 [58.92-68.26],67.32 [62.74-72.1],71.37 [66.74-76.24],75.63 [70.94-80.62]
7,Brazil,14.7 [12.91-16.75],14.94 [13.48-16.58],15.16 [14-16.41],15.39 [14.49-16.34],16.75 [15.99-17.53],15.95 [15.39-16.51],16.3 [15.87-16.74],16.72 [16.36-17.08],17.24 [16.9-17.59],...,19.55 [18.86-20.27],20.61 [19.68-21.6],21.84 [20.67-23.07],23.24 [21.85-24.7],24.8 [23.21-26.49],26.53 [24.8-28.42],28.43 [26.53-30.43],30.41 [28.39-32.57],32.52 [30.36-34.8],34.73 [32.47-37.14]
8,British Virgin Islands,10.85 [5.05-22.86],11.18 [5.39-22.97],11.55 [5.71-23.09],11.89 [6.05-23.36],12.29 [6.4-23.42],12.69 [6.82-23.42],13.06 [7.23-23.43],13.44 [7.64-23.54],13.8 [8.08-23.45],...,14.8 [9.45-23.05],15.05 [9.93-22.76],15.25 [10.39-22.34],15.33 [10.84-21.72],15.4 [11.24-21.11],15.45 [11.62-20.53],15.47 [11.94-20.11],15.55 [12.22-19.81],15.63 [12.49-19.55],15.74 [12.71-19.42]
9,Canada,5.11 [4.97-5.27],5.18 [5.06-5.29],5.23 [5.13-5.32],5.28 [5.19-5.37],5.33 [5.24-5.42],5.39 [5.29-5.48],5.45 [5.35-5.54],5.51 [5.42-5.6],5.58 [5.48-5.68],...,5.8 [5.7-5.9],5.88 [5.78-5.98],5.96 [5.86-6.07],6.03 [5.93-6.15],6.1 [5.99-6.21],6.14 [6.03-6.25],6.17 [6.06-6.27],6.18 [6.08-6.29],6.2 [6.09-6.3],6.23 [6.12-6.34]
10,Chile,6.85 [6.06-7.73],7.15 [6.54-7.77],7.4 [6.89-7.92],7.61 [7.19-8.05],7.79 [7.45-8.15],7.96 [7.72-8.2],8.11 [7.91-8.31],8.25 [8.06-8.44],8.39 [8.2-8.58],...,8.82 [8.62-9.04],8.88 [8.68-9.08],8.91 [8.71-9.1],8.96 [8.76-9.18],9.1 [8.91-9.29],9.29 [9.07-9.51],9.51 [9.3-9.72],9.81 [9.59-10.03],10.26 [10.02-10.51],10.89 [10.66-11.13]
11,Colombia,13.25 [9.02-19.5],13.72 [9.64-19.42],14.14 [10.31-19.36],14.62 [11.04-19.3],15.09 [11.74-19.35],15.6 [12.47-19.43],16.12 [13.21-19.6],16.66 [13.94-19.85],17.23 [14.68-20.15],...,19 [16.9-21.36],19.62 [17.58-21.9],20.24 [18.26-22.48],20.87 [18.96-23.06],21.52 [19.61-23.65],22.17 [20.28-24.27],22.84 [20.96-24.94],23.55 [21.65-25.59],24.29 [22.38-26.32],25.07 [23.13-27.1]
12,Costa Rica,7.92 [7.52-8.34],8.2 [7.9-8.5],8.44 [8.19-8.7],8.66 [8.41-8.91],8.87 [8.61-9.13],9.08 [8.83-9.34],9.32 [9.06-9.58],9.6 [9.35-9.86],9.92 [9.66-10.18],...,10.73 [10.46-11.01],10.92 [10.64-11.2],11.07 [10.8-11.35],11.2 [10.92-11.48],11.34 [11.06-11.62],11.52 [11.24-11.81],11.78 [11.51-12.07],12.14 [11.86-12.44],12.59 [12.3-12.89],13.11 [12.82-13.41]
13,Cuba,5.11 [4.24-6.28],5.22 [4.4-6.25],5.32 [4.57-6.23],5.43 [4.73-6.24],5.54 [4.89-6.28],5.65 [5.04-6.36],5.78 [5.19-6.46],5.91 [5.32-6.58],6.05 [5.46-6.71],...,6.54 [5.89-7.21],6.73 [6.07-7.42],6.94 [6.24-7.64],7.15 [6.43-7.88],7.38 [6.64-8.13],7.64 [6.87-8.42],7.9 [7.1-8.72],8.18 [7.35-9.03],8.49 [7.62-9.37],8.81 [7.92-9.73]
14,Dominica,35.62 [30.55-41.55],35.18 [30.48-40.7],34.51 [30.13-39.61],33.6 [29.57-38.27],32.47 [28.81-36.75],31.22 [27.92-35.07],29.88 [26.89-33.36],28.51 [25.8-31.63],27.16 [24.7-29.92],...,23.44 [21.58-25.47],22.39 [20.67-24.23],21.42 [19.81-23.13],20.53 [19.04-22.13],19.73 [18.32-21.24],19.02 [17.67-20.46],18.38 [17.09-19.75],17.82 [16.59-19.14],17.34 [16.16-18.62],16.93 [15.78-18.17]
15,Dominican Republic,33.74 [25.61-44.03],34.34 [26.73-43.65],34.76 [27.75-43.26],35.05 [28.59-42.64],35.09 [29.16-41.81],35.09 [29.69-41.07],35.1 [30.18-40.38],35.09 [30.57-39.92],35.12 [30.97-39.53],...,35.36 [31.92-39],35.53 [32.29-39.04],35.77 [32.69-39.19],36.09 [33.14-39.37],36.49 [33.55-39.67],36.95 [34.03-40.02],37.51 [34.6-40.59],38.24 [35.32-41.31],39.06 [36.11-42.18],40.05 [37.07-43.23]
16,Ecuador,12.93 [11.74-14.25],13.41 [12.53-14.35],13.88 [13.29-14.51],14.35 [13.94-14.78],14.84 [14.37-15.32],15.37 [14.65-16.1],15.95 [14.93-17.01],16.6 [15.29-18.02],17.33 [15.72-19.1],...,19.87 [17.47-22.54],20.77 [18.18-23.71],21.68 [18.91-24.83],22.6 [19.66-25.96],23.52 [20.48-26.98],24.47 [21.34-28.05],25.52 [22.35-29.09],26.7 [23.52-30.31],28.06 [24.81-31.76],29.63 [26.26-33.44]
17,El Salvador,12.84 [7.91-21.23],13.32 [8.51-21.18],13.78 [9.09-21.2],14.28 [9.69-21.34],14.83 [10.38-21.41],15.41 [11.07-21.56],16.03 [11.8-21.88],16.74 [12.64-22.26],17.53 [13.55-22.69],...,20.31 [16.79-24.42],21.38 [17.99-25.33],22.49 [19.26-26.26],23.71 [20.59-27.37],25.02 [21.92-28.62],26.43 [23.34-29.95],27.96 [24.85-31.47],29.59 [26.4-33.15],31.31 [28.03-34.84],33.14 [29.78-36.7]
18,Grenada,16.38 [13.79-19.38],16.46 [14.22-19.02],16.45 [14.53-18.61],16.39 [14.72-18.24],16.31 [14.76-18],16.19 [14.73-17.83],16.06 [14.64-17.68],15.9 [14.48-17.48],15.73 [14.31-17.33],...,15.3 [13.92-16.86],15.2 [13.82-16.75],15.14 [13.78-16.67],15.12 [13.77-16.62],15.13 [13.79-16.61],15.14 [13.82-16.62],15.17 [13.84-16.63],15.21 [13.89-16.67],15.28 [13.94-16.75],15.4 [14.04-16.88]
19,Guatemala,23.8 [17.7-31.68],24.57 [19-31.52],25.44 [20.28-31.75],26.35 [21.65-32.11],27.35 [22.97-32.48],28.39 [24.32-33.16],29.51 [25.58-34.06],30.76 [26.88-35.12],32.05 [28.3-36.3],...,36.28 [32.73-40.22],37.8 [34.29-41.69],39.39 [35.88-43.24],41.02 [37.51-44.86],42.7 [39.18-46.54],44.44 [40.86-48.31],46.22 [42.62-50.17],48.12 [44.41-52.1],50.06 [46.32-54.09],52.12 [48.34-56.18]
20,Guyana,28.53 [17.01-48.27],29.43 [18.15-47.98],30.32 [19.39-47.98],31.28 [20.63-47.87],32.18 [21.88-47.98],33.11 [23.21-48.23],34.12 [24.46-48.42],35 [25.75-48.34],35.86 [27.06-48.12],...,38.07 [31.29-46.87],38.84 [32.56-46.7],39.67 [33.82-46.85],40.53 [35.05-47.1],41.39 [36.17-47.46],42.31 [37.34-48.01],43.25 [38.51-48.8],44.31 [39.63-49.72],45.43 [40.72-50.69],46.6 [41.88-51.79]
21,Haiti,60.51 [44.07-84.47],62.5 [47.12-84.02],64.37 [50.28-83.77],66.34 [53.43-84.05],68.21 [56.34-84.12],70.13 [59.29-84.82],71.98 [61.81-85.56],73.9 [64.23-86.11],75.77 [66.55-86.84],...,81.38 [73.61-90],83.29 [75.74-91.44],85.21 [77.95-93.08],87.31 [80.06-94.97],89.53 [82.16-97.18],91.87 [84.39-99.61],94.45 [86.91-102.31],97.29 [89.61-105.2],100.46 [92.67-108.45],103.87 [96.06-111.93]
22,Honduras,17.14 [13.44-22.38],17.76 [14.28-22.65],18.4 [15.1-22.9],19.06 [15.87-23.33],19.77 [16.68-23.75],20.52 [17.55-24.18],21.29 [18.42-24.75],22.08 [19.31-25.35],22.89 [20.22-26.01],...,25.61 [23.05-28.44],26.62 [24.06-29.43],27.67 [25.14-30.43],28.82 [26.24-31.58],30.04 [27.43-32.8],31.36 [28.7-34.13],32.75 [30.07-35.59],34.25 [31.5-37.16],35.81 [33.01-38.83],37.46 [34.54-40.57]
23,Jamaica,12.83 [6.78-24.48],13.25 [7.28-24.57],13.7 [7.78-24.6],14.13 [8.36-24.68],14.57 [8.92-24.69],15 [9.53-24.68],15.43 [10.16-24.52],15.88 [10.79-24.4],16.35 [11.45-24.29],...,17.69 [13.4-24.09],18.07 [13.95-24.01],18.39 [14.48-23.91],18.67 [14.96-23.66],18.93 [15.41-23.52],19.24 [15.83-23.48],19.58 [16.31-23.54],19.97 [16.76-23.76],20.41 [17.28-24.08],20.93 [17.82-24.51]
24,Mexico,13.71 [12.08-15.49],14.16 [12.85-15.61],14.66 [13.52-15.86],15.17 [14.15-16.25],15.68 [14.77-16.7],16.21 [15.38-17.21],16.76 [15.97-17.76],17.33 [16.53-18.36],17.93 [17.08-19],...,19.84 [18.72-21.05],20.54 [19.3-21.83],21.27 [19.93-22.66],22.05 [20.59-23.57],22.89 [21.3-24.52],23.8 [22.09-25.55],24.79 [22.99-26.66],25.87 [23.98-27.83],27.04 [25.05-29.08],28.29 [26.19-30.41]
25,Montserrat,5.44 [2.07-14.46],5.62 [2.19-14.58],5.81 [2.33-14.8],6.01 [2.45-14.96],6.22 [2.58-15.13],6.42 [2.73-15.29],6.65 [2.9-15.34],6.87 [3.09-15.36],7.09 [3.28-15.51],...,7.84 [3.92-15.9],8.12 [4.15-16.08],8.4 [4.38-16.26],8.69 [4.63-16.37],9.01 [4.93-16.55],9.31 [5.25-16.63],9.67 [5.61-16.73],10.05 [5.97-16.86],10.47 [6.39-17.05],10.9 [6.87-17.21]
26,Nicaragua,14.03 [12.55-15.75],14.9 [13.71-16.45],15.82 [14.88-17.29],16.77 [15.93-18.21],17.77 [16.86-19.26],18.78 [17.67-20.36],19.81 [18.43-21.5],20.83 [19.19-22.65],21.9 [19.96-23.82],...,25.21 [22.57-27.85],26.39 [23.55-29.25],27.63 [24.6-30.69],28.95 [25.73-32.16],30.31 [26.95-33.64],31.76 [28.23-35.23],33.34 [29.72-36.82],35.02 [31.37-38.62],36.86 [33.12-40.58],38.85 [35.08-42.68]
27,Panama,14.37 [7.4-28.07],14.85 [7.92-28.08],15.35 [8.46-28.23],15.9 [9-28.27],16.44 [9.65-28.23],16.93 [10.32-28.23],17.48 [11-28.06],18.01 [11.76-28.13],18.61 [12.51-28.13],...,20.47 [15.03-28.04],21.09 [15.85-28.09],21.71 [16.72-28.28],22.35 [17.47-28.46],22.94 [18.25-28.58],23.55 [19.08-28.77],24.16 [19.88-29],24.77 [20.67-29.31],25.4 [21.46-29.64],26.01 [22.2-29.95]
28,Paraguay,18.74 [9.33-38.7],19.36 [9.88-38.7],20.02 [10.52-38.76],20.75 [11.18-38.84],21.43 [11.81-39.11],22.19 [12.55-39.18],22.89 [13.43-39.23],23.63 [14.34-39.5],24.4 [15.3-39.61],...,26.76 [18.17-39.82],27.55 [19.14-39.88],28.36 [20.22-39.97],29.16 [21.21-40.06],29.94 [22.32-39.94],30.75 [23.46-39.84],31.52 [24.65-39.86],32.29 [25.85-40.05],33.08 [27-40.23],33.83 [28.13-40.5]
29,Peru,14.54 [11.9-17.99],14.92 [12.54-17.98],15.31 [13.18-17.92],15.69 [13.82-17.91],16.1 [14.48-17.97],16.55 [15.06-18.18],17.05 [15.69-18.54],17.62 [16.32-19.01],18.29 [16.99-19.62],...,20.95 [19.65-22.29],22.1 [20.78-23.48],23.41 [21.99-24.84],24.85 [23.34-26.38],26.45 [24.84-28.1],28.23 [26.51-30.01],30.24 [28.46-32.13],32.54 [30.61-34.51],35.15 [33.11-37.24],38.13 [35.96-40.34]
30,Saint Kitts and Nevis,15.02 [10.35-22.12],15.44 [11.03-21.97],15.86 [11.7-21.75],16.26 [12.42-21.53],16.61 [13.13-21.25],16.94 [13.76-21.04],17.19 [14.31-20.78],17.31 [14.77-20.44],17.38 [15.04-20.14],...,17.63 [15.45-20.18],17.83 [15.63-20.39],18.12 [15.91-20.69],18.53 [16.29-21.11],19.09 [16.8-21.72],19.8 [17.43-22.44],20.65 [18.26-23.37],21.64 [19.2-24.39],22.71 [20.22-25.49],23.81 [21.26-26.61]
31,Saint Lucia,24.48 [21.23-28.21],24.06 [21.16-27.33],23.57 [21.02-26.42],23.04 [20.81-25.52],22.5 [20.55-24.65],21.95 [20.21-23.86],21.43 [19.87-23.12],20.95 [19.51-22.5],20.49 [19.16-21.96],...,19.38 [18.21-20.68],19.1 [17.95-20.36],18.85 [17.71-20.09],18.65 [17.53-19.88],18.5 [17.38-19.69],18.39 [17.28-19.55],18.32 [17.24-19.46],18.3 [17.24-19.43],18.33 [17.29-19.43],18.41 [17.38-19.51]
32,Saint Vincent and the Grenadines,14.16 [10.74-18.57],14.64 [11.51-18.6],15.17 [12.33-18.59],15.68 [13.14-18.7],16.25 [13.97-18.84],16.82 [14.83-19.06],17.41 [15.59-19.43],18.02 [16.31-19.9],18.64 [16.98-20.5],...,20.37 [18.67-22.2],20.79 [19.1-22.64],21.12 [19.44-22.94],21.36 [19.69-23.18],21.53 [19.84-23.32],21.68 [19.99-23.49],21.84 [20.15-23.64],21.98 [20.33-23.78],22.15 [20.51-23.94],22.3 [20.67-24.07]
33,Suriname,17.71 [11.51-27.72],18.26 [12.15-27.98],18.78 [12.84-28.05],19.37 [13.57-28.06],19.94 [14.32-28.07],20.48 [15.05-28.12],21.02 [15.8-28.03],21.6 [16.49-28.12],22.14 [17.18-28.34],...,23.89 [19.34-29.37],24.55 [20.08-29.93],25.22 [20.74-30.54],25.91 [21.41-31.15],26.67 [22.14-31.86],27.48 [22.86-32.64],28.35 [23.69-33.5],29.27 [24.6-34.5],30.27 [25.55-35.55],31.31 [26.61-36.7]
34,Trinidad and Tobago,16.81 [7.12-41.8],17.39 [7.55-41.78],17.91 [7.96-42.06],18.46 [8.53-42.36],19.03 [9.07-42.68],19.64 [9.6-42.9],20.23 [10.24-43.01],20.85 [10.9-43.21],21.53 [11.55-43.24],...,23.54 [13.93-43.6],24.21 [14.87-43.51],24.9 [15.77-43.68],25.6 [16.64-43.74],26.19 [17.45-43.65],26.81 [18.21-43.13],27.27 [19.01-42.55],27.68 [19.72-41.44],27.94 [20.38-40.18],28.13 [21.04-38.72]
35,Turks and Caicos Islands,4.63 [2.82-7.65],4.77 [2.98-7.66],4.9 [3.16-7.61],5.03 [3.36-7.55],5.15 [3.55-7.5],5.27 [3.76-7.41],5.41 [3.96-7.39],5.55 [4.16-7.42],5.7 [4.34-7.48],...,6.18 [4.87-7.86],6.36 [5.05-8.06],6.56 [5.24-8.29],6.79 [5.45-8.55],7.04 [5.67-8.86],7.32 [5.91-9.19],7.63 [6.16-9.59],7.95 [6.43-9.98],8.31 [6.73-10.41],8.69 [7.02-10.84]
36,United States of America,6.35 [6.1-6.6],6.44 [6.27-6.63],6.53 [6.4-6.67],6.62 [6.5-6.74],6.71 [6.59-6.82],6.79 [6.68-6.91],6.88 [6.76-6.99],6.97 [6.86-7.09],7.08 [6.96-7.2],...,7.48 [7.35-7.6],7.61 [7.49-7.74],7.74 [7.62-7.87],7.86 [7.73-7.99],7.96 [7.83-8.1],8.05 [7.92-8.19],8.14 [8.01-8.28],8.23 [8.1-8.37],8.33 [8.19-8.47],8.45 [8.31-8.59]
37,Uruguay,6.28 [5.86-6.73],6.8 [6.46-7.15],7.35 [7.06-7.65],7.9 [7.62-8.18],8.43 [8.14-8.71],8.91 [8.62-9.2],9.34 [9.04-9.65],9.7 [9.39-10.04],10.03 [9.7-10.39],...,11.28 [10.92-11.64],11.92 [11.57-12.29],12.71 [12.34-13.07],13.57 [13.19-13.95],14.43 [14.05-14.81],15.2 [14.82-15.59],15.78 [15.38-16.18],16.2 [15.8-16.62],16.59 [16.17-17.01],17.04 [16.65-17.47]
38,Venezuela (Bolivarian Republic of),24.23 [18.77-31.22],24.23 [19.73-29.76],24.23 [20.66-28.45],24.23 [21.52-27.29],24.22 [22.34-26.29],19.14 [18.16-20.18],18 [17.43-18.59],17.62 [17.24-18.02],17.34 [16.99-17.69],...,17.05 [16.73-17.39],17.17 [16.84-17.51],17.46 [17.13-17.79],17.91 [17.58-18.25],18.5 [18.14-18.85],19.15 [18.79-19.5],19.78 [19.41-20.15],20.33 [19.95-20.71],20.87 [20.48-21.26],21.51 [21.1-21.93]

In [49]:
### Delete part after the split character "[" for all columns
final_df2 = df2_pivot[keep_columns]
# Split columns
for column in final_df2.columns:
    final_df2[column] = final_df2[column].str.split('[').str[0]
    
print(final_df2)

                             Countries    2020    2019    2018    2017  \
0                             Anguilla   4.18    4.33    4.49    4.64
1                  Antigua and Barbuda   6.36    6.59    6.84    7.12
2                            Argentina    7.7    8.58    9.45   10.25
3                              Bahamas  13.32   23.42   13.53   13.63
4                             Barbados  12.29   12.66   13.04   13.43
5                               Belize   11.7    12.3   12.98   13.73
6     Bolivia (Plurinational State of)  25.63   26.59   27.72   28.92
7                               Brazil   14.7   14.94   15.16   15.39
8               British Virgin Islands  10.85   11.18   11.55   11.89
9                               Canada   5.11    5.18    5.23    5.28
10                               Chile   6.85    7.15     7.4    7.61
11                            Colombia  13.25   13.72   14.14   14.62
12                          Costa Rica   7.92     8.2    8.44    8.66
13                                Cuba   5.11    5.22    5.32    5.43
14                            Dominica  35.62   35.18   34.51    33.6
15                  Dominican Republic  33.74   34.34   34.76   35.05
16                             Ecuador  12.93   13.41   13.88   14.35
17                         El Salvador  12.84   13.32   13.78   14.28
18                             Grenada  16.38   16.46   16.45   16.39
19                           Guatemala   23.8   24.57   25.44   26.35
20                              Guyana  28.53   29.43   30.32   31.28
21                               Haiti  60.51    62.5   64.37   66.34
22                            Honduras  17.14   17.76    18.4   19.06
23                             Jamaica  12.83   13.25    13.7   14.13
24                              Mexico  13.71   14.16   14.66   15.17
25                          Montserrat   5.44    5.62    5.81    6.01
26                           Nicaragua  14.03    14.9   15.82   16.77
27                              Panama  14.37   14.85   15.35    15.9
28                            Paraguay  18.74   19.36   20.02   20.75
29                                Peru  14.54   14.92   15.31   15.69
30               Saint Kitts and Nevis  15.02   15.44   15.86   16.26
31                         Saint Lucia  24.48   24.06   23.57   23.04
32    Saint Vincent and the Grenadines  14.16   14.64   15.17   15.68
33                            Suriname  17.71   18.26   18.78   19.37
34                 Trinidad and Tobago  16.81   17.39   17.91   18.46
35            Turks and Caicos Islands   4.63    4.77     4.9    5.03
36            United States of America   6.35    6.44    6.53    6.62
37                             Uruguay   6.28     6.8    7.35     7.9
38  Venezuela (Bolivarian Republic of)  24.23   24.23   24.23   24.23

      2016    2015    2014    2013    2012  ...    2009    2008    2007  \
0     4.8    4.97    5.14    5.33    5.55   ...   6.34    6.62    6.91
1    7.43    7.75    8.13    8.55    9.02   ...   10.6   11.16   11.75
2   10.97   11.59   12.17   12.75   13.34   ...  14.96   15.37   15.72
3   13.76   13.93   14.15   14.41   14.72   ...  15.82    16.2   16.53
4   13.77   14.07   14.35   14.55   14.74   ...  15.14   15.31   15.47
5   14.51   15.32   16.12   16.93   17.68   ...  19.45   19.88   20.26
6    30.2   31.64   33.33   35.22    37.3   ...  44.44   47.13      50
7   16.75   15.95    16.3   16.72   17.24   ...  19.55   20.61   21.84
8   12.29   12.69   13.06   13.44    13.8   ...   14.8   15.05   15.25
9    5.33    5.39    5.45    5.51    5.58   ...    5.8    5.88    5.96
10   7.79    7.96    8.11    8.25    8.39   ...   8.82    8.88    8.91
11  15.09    15.6   16.12   16.66   17.23   ...     19   19.62   20.24
12   8.87    9.08    9.32     9.6    9.92   ...  10.73   10.92   11.07
13   5.54    5.65    5.78    5.91    6.05   ...   6.54    6.73    6.94
14  32.47   31.22   29.88   28.51   27.16   ...  23.44   22.39   21.42
15  35.09   35.09    35.1   35.09   35.12   ...  35.36   35.53   35.77
16  14.84   15.37   15.95    16.6   17.33   ...  19.87   20.77   21.68
17  14.83   15.41   16.03   16.74   17.53   ...  20.31   21.38   22.49
18  16.31   16.19   16.06    15.9   15.73   ...   15.3    15.2   15.14
19  27.35   28.39   29.51   30.76   32.05   ...  36.28    37.8   39.39
20  32.18   33.11   34.12      35   35.86   ...  38.07   38.84   39.67
21  68.21   70.13   71.98    73.9   75.77   ...  81.38   83.29   85.21
22  19.77   20.52   21.29   22.08   22.89   ...  25.61   26.62   27.67
23  14.57      15   15.43   15.88   16.35   ...  17.69   18.07   18.39
24  15.68   16.21   16.76   17.33   17.93   ...  19.84   20.54   21.27
25   6.22    6.42    6.65    6.87    7.09   ...   7.84    8.12     8.4
26  17.77   18.78   19.81   20.83    21.9   ...  25.21   26.39   27.63
27  16.44   16.93   17.48   18.01   18.61   ...  20.47   21.09   21.71
28  21.43   22.19   22.89   23.63    24.4   ...  26.76   27.55   28.36
29   16.1   16.55   17.05   17.62   18.29   ...  20.95    22.1   23.41
30  16.61   16.94   17.19   17.31   17.38   ...  17.63   17.83   18.12
31   22.5   21.95   21.43   20.95   20.49   ...  19.38    19.1   18.85
32  16.25   16.82   17.41   18.02   18.64   ...  20.37   20.79   21.12
33  19.94   20.48   21.02    21.6   22.14   ...  23.89   24.55   25.22
34  19.03   19.64   20.23   20.85   21.53   ...  23.54   24.21    24.9
35   5.15    5.27    5.41    5.55     5.7   ...   6.18    6.36    6.56
36   6.71    6.79    6.88    6.97    7.08   ...   7.48    7.61    7.74
37   8.43    8.91    9.34     9.7   10.03   ...  11.28   11.92   12.71
38  24.22   19.14      18   17.62   17.34   ...  17.05   17.17   17.46

      2006    2005    2004    2003    2002     2001     2000
0    7.23    7.56    7.92    8.31    8.71     9.12     9.57
1   12.34   12.94   13.53    14.1   14.65    15.12    15.53
2   16.11   16.59   17.13   17.72   18.34    18.99    19.68
3   16.79   16.92   16.91   16.79    16.6    16.41     16.3
4   15.63   15.74   15.78   15.72   15.59    15.38    15.16
5    20.6   20.92   21.28    21.7   22.21    22.85    23.61
6   53.07   56.34   59.79   63.46   67.32    71.37    75.63
7   23.24    24.8   26.53   28.43   30.41    32.52    34.73
8   15.33    15.4   15.45   15.47   15.55    15.63    15.74
9    6.03     6.1    6.14    6.17    6.18      6.2     6.23
10   8.96     9.1    9.29    9.51    9.81    10.26    10.89
11  20.87   21.52   22.17   22.84   23.55    24.29    25.07
12   11.2   11.34   11.52   11.78   12.14    12.59    13.11
13   7.15    7.38    7.64     7.9    8.18     8.49     8.81
14  20.53   19.73   19.02   18.38   17.82    17.34    16.93
15  36.09   36.49   36.95   37.51   38.24    39.06    40.05
16   22.6   23.52   24.47   25.52    26.7    28.06    29.63
17  23.71   25.02   26.43   27.96   29.59    31.31    33.14
18  15.12   15.13   15.14   15.17   15.21    15.28     15.4
19  41.02    42.7   44.44   46.22   48.12    50.06    52.12
20  40.53   41.39   42.31   43.25   44.31    45.43     46.6
21  87.31   89.53   91.87   94.45   97.29   100.46   103.87
22  28.82   30.04   31.36   32.75   34.25    35.81    37.46
23  18.67   18.93   19.24   19.58   19.97    20.41    20.93
24  22.05   22.89    23.8   24.79   25.87    27.04    28.29
25   8.69    9.01    9.31    9.67   10.05    10.47     10.9
26  28.95   30.31   31.76   33.34   35.02    36.86    38.85
27  22.35   22.94   23.55   24.16   24.77     25.4    26.01
28  29.16   29.94   30.75   31.52   32.29    33.08    33.83
29  24.85   26.45   28.23   30.24   32.54    35.15    38.13
30  18.53   19.09    19.8   20.65   21.64    22.71    23.81
31  18.65    18.5   18.39   18.32    18.3    18.33    18.41
32  21.36   21.53   21.68   21.84   21.98    22.15     22.3
33  25.91   26.67   27.48   28.35   29.27    30.27    31.31
34   25.6   26.19   26.81   27.27   27.68    27.94    28.13
35   6.79    7.04    7.32    7.63    7.95     8.31     8.69
36   7.86    7.96    8.05    8.14    8.23     8.33     8.45
37  13.57   14.43    15.2   15.78    16.2    16.59    17.04
38  17.91    18.5   19.15   19.78   20.33    20.87    21.51

[39 rows x 22 columns]

C:\Users\esspe\AppData\Local\Temp\ipykernel_16212\1695543427.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df2[column] = final_df2[column].str.split('[').str[0]

In [50]:
## Check the dataset after all the changes
final_df2.head(10)

,Countries,2020,2019,2018,2017,2016,2015,2014,2013,2012,...,2009,2008,2007,2006,2005,2004,2003,2002,2001,2000
0,Anguilla,4.18,4.33,4.49,4.64,4.8,4.97,5.14,5.33,5.55,...,6.34,6.62,6.91,7.23,7.56,7.92,8.31,8.71,9.12,9.57
1,Antigua and Barbuda,6.36,6.59,6.84,7.12,7.43,7.75,8.13,8.55,9.02,...,10.6,11.16,11.75,12.34,12.94,13.53,14.1,14.65,15.12,15.53
2,Argentina,7.7,8.58,9.45,10.25,10.97,11.59,12.17,12.75,13.34,...,14.96,15.37,15.72,16.11,16.59,17.13,17.72,18.34,18.99,19.68
3,Bahamas,13.32,23.42,13.53,13.63,13.76,13.93,14.15,14.41,14.72,...,15.82,16.2,16.53,16.79,16.92,16.91,16.79,16.6,16.41,16.3
4,Barbados,12.29,12.66,13.04,13.43,13.77,14.07,14.35,14.55,14.74,...,15.14,15.31,15.47,15.63,15.74,15.78,15.72,15.59,15.38,15.16
5,Belize,11.7,12.3,12.98,13.73,14.51,15.32,16.12,16.93,17.68,...,19.45,19.88,20.26,20.6,20.92,21.28,21.7,22.21,22.85,23.61
6,Bolivia (Plurinational State of),25.63,26.59,27.72,28.92,30.2,31.64,33.33,35.22,37.3,...,44.44,47.13,50,53.07,56.34,59.79,63.46,67.32,71.37,75.63
7,Brazil,14.7,14.94,15.16,15.39,16.75,15.95,16.3,16.72,17.24,...,19.55,20.61,21.84,23.24,24.8,26.53,28.43,30.41,32.52,34.73
8,British Virgin Islands,10.85,11.18,11.55,11.89,12.29,12.69,13.06,13.44,13.8,...,14.8,15.05,15.25,15.33,15.4,15.45,15.47,15.55,15.63,15.74
9,Canada,5.11,5.18,5.23,5.28,5.33,5.39,5.45,5.51,5.58,...,5.8,5.88,5.96,6.03,6.1,6.14,6.17,6.18,6.2,6.23

In [51]:
# Save the modified DataFrame to a new CSV file
# final_df2.to_csv('new_child_mortality_americas.csv', index=False)

### Step 3 - Repeat the data transformations under Step 2 for all the other WHO regions
We've prepared the data for the Region of the Americas. 
We need to do it for the African region, Eastern mediterranean region, European region, South-east asian region, Western pacific region. Go ahead and preprocess the data one region at a time.

In [ ]:
## See the next Notebook